CHANGELOG.md
framework/Operations.xcodeproj/project.pbxproj
framework/Operations/Conditions/BlockCondition.swift
framework/OperationsTests/BlockConditionTests.swift
framework/OperationsTests/CloudConditionTests.swift

Only execute the operation if the result of running a block is true.

Block Condition

---

framework/Operations.xcodeproj/project.pbxproj
framework/Operations/Operations/CloudKitOperation.swift
framework/OperationsTests/BlockConditionTests.swift
framework/OperationsTests/CloudKitOperationTests.swift

We want `CKDatabaseOperation` to take part in Operations features.

Support wrapping up CKDatabaseOperation

---

Operations/Conditions/Permissions/AddressBookCondition.swift
Operations/Operations/AddressBookOperation.swift

Expand the AddressBook operations

---

Operations/Operations/AddressBookOperation.swift

Address Book operations pt II

---

Operations/Operations/Operation.swift
Operations/Queue/OperationQueue.swift
OperationsTests/ReachableOperationTests.swift

I liked @jshier's suggestion, and improved the code straight away.

Use forEach method instead of 'for .. in ..'.

---

Operations.podspec
Operations.xcodeproj/project.pbxproj
Operations/Conditions/OperationCondition.swift
Operations/Operations/Operation.swift
Operations/Operations/UIOperation.swift
OperationsTests/OperationTests.swift
OperationsTests/ReachableOperationTests.swift

Bring Swift 2.0 up to date (again)

---

Operations/AddressBook/AddressBook.swift

There are a few things missing.

Fix and fill out AddressBookPerson properties

---

Operations/AddressBook/AddressBook.swift

With Address Book related changes.

Update Swift 2.0 branch

---

OperationsTests/LocationOperationsTests.swift

For some reason these always seem to fail in CI

Improve reliability of Location related unit tests

---

Operations/Extras/AddressBook/iOS/AddressBook.swift

Some of the C function calls which return `Unmanaged<T>!` are not unwrapping correctly.

Bug, AddressBook has some strange behavior with Swift 2.0 & when build against iOS 9.

---

Operations.xcodeproj/project.pbxproj
Operations/Features/Shared/NetworkOperation.swift

In the original Advanced NSOperation project there is a wrapper for an `NSURLSessionTask` which we don't actually have yet.

NSURLSessionTask Operation

---

.buildkite/pipeline.template.yml
.scripts/update-bundler.sh
Operations.xcodeproj/project.pbxproj
Operations/Features/Shared/Reachability.swift
OperationsTests/Features/ReachabilityTests.swift

Can move a bunch of functionality out of the `Reachability` object and into extensions which are then easily testable.

Test Coverage Blitz, Low Hanging Fruit #1 - Reachability

---

Operations.xcodeproj/project.pbxproj
Operations/Core/Shared/Operation.swift
Operations/Core/iOS/UIOperation.swift
Operations/Extras/AddressBook/iOS/AddressBook.swift
Operations/Extras/AddressBook/iOS/AddressBookOperations.swift
OperationsTests/Core/AlertOperationTests.swift
OperationsTests/Core/NegatedConditionTests.swift
OperationsTests/Core/NoFailedDependenciesConditionTests.swift
OperationsTests/Core/OperationTests.swift
OperationsTests/Core/UIOperationTests.swift
OperationsTests/Extras/AddressBook/AddressBookConditionTests.swift
OperationsTests/Extras/AddressBook/AddressBookTests.swift

Address Book related stuff is the least well covered.

Test Coverage Blitz - Get some low hanging fruit

---

.jazzy.yml
Operations.xcodeproj/project.pbxproj
Operations/Core/Shared/Logging.swift
Operations/Core/Shared/Operation.swift
Operations/Core/Shared/OperationCondition.swift
Operations/Features/Shared/CalendarCapability.swift
Operations/Features/Shared/Capability.swift
Operations/Features/Shared/CloudCapability.swift
Operations/Features/iOS/HealthCapability.swift
Operations/Features/iOS/LocationCapability.swift
Operations/Features/iOS/LocationOperations.swift
Operations/Features/iOS/PassbookCapability.swift
Operations/Features/iOS/PhotosCapability.swift
OperationsTests/Features/HealthCapabilityTests.swift

Aim to add docs to Capabilities - target ~ 60% doc coverage

Documentation Blitz #2

---

Sources/Core/Shared/BlockOperation.swift
Sources/Core/Shared/GroupOperation.swift
Sources/Core/Shared/Operation.swift
Tests/Core/OperationTests.swift

This is a work in progress on my investigation into this bug.

Bug: completion block is called twice

---

Sources/Core/Shared/BlockOperation.swift
Sources/Core/Shared/Logging.swift
Sources/Core/Shared/Operation.swift
Sources/Features/iOS/LocationOperations.swift
Tests/Core/LoggingTests.swift
examples/Permissions/Permissions/AppDelegate.swift
examples/Permissions/Podfile.lock
examples/Permissions/Pods/Local Podspecs/Operations.podspec.json
examples/Permissions/Pods/Manifest.lock
examples/Permissions/Pods/Pods.xcodeproj/project.pbxproj
examples/Permissions/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Operations.xcscheme
examples/Permissions/Pods/Target Support Files/Operations/Info.plist

Update features of Logger

---

Sources/Core/Shared/BlockOperation.swift
Sources/Core/Shared/Operation.swift

This is another attempt to address the underlying problem causing #123.

Completion block called twice

---

Sources/Core/Shared/BlockOperation.swift
Sources/Core/Shared/DelayOperation.swift
Sources/Core/Shared/Operation.swift
Tests/Core/LoggingObserverTests.swift
Tests/Core/OperationTests.swift

Cancellation issues with Delay and Block operations

---

Operations.xcodeproj/project.pbxproj
Sources/Core/Shared/Operation.swift
Sources/Core/Shared/OperationQueue.swift
Sources/Core/Shared/ResultInjection.swift
Tests/Core/OperationTests.swift
Tests/Core/ResultInjectionTests.swift
examples/Permissions/Permissions/MainController.swift
examples/Permissions/Pods/Pods.xcodeproj/project.pbxproj
examples/Permissions/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Operations.xcscheme

This is a work in progress for the discussion in #135.

Result Injection

---

Sources/Core/Shared/Operation.swift

There is a subtle issue where assessing `isReady` of an Operation can trigger state changes which affect `ready` - and so we can get invalid state changes.

Ensure thread safety when assessing Operation readiness 

---

Sources/Core/Shared/Operation.swift

This is to address the discussion in #152.

Sanity checking addObserver

---

Sources/Core/Shared/ExclusivityManager.swift
Sources/Core/Shared/OperationQueue.swift
Tests/Core/MutualExclusiveTests.swift
Tests/Core/OperationTests.swift

This is to address the issue in #129.
If a mutually exclusive condition has a dependency operation, we use this `NSOperation` as the mututally exclusive operation instead of the receiver operation.
There are a few changes here compared to the code suggested in #129:
1. I've written it assuming that #157 will be merged.
2. The ExclusivityManager ensures that the category is removed when the operation ends. This is done using either an observer if its an `Operation` subclass, or using a completion block.
3. When #157 is merged, the mutual exclusion stuff should be moved to earlier in the method before the dependencies are added to the queue.

Add mutual exclusion to a condition's dependency.

---

Sources/Features/Shared/Reachability.swift
Sources/Features/Shared/ReachabilityCondition.swift
Sources/Features/Shared/ReachableOperation.swift
Tests/Features/ReachabilityConditionTests.swift
Tests/Features/ReachabilityTests.swift
Tests/Features/ReachableOperationTests.swift

File | % Before | % After
------|------------|------------
ReachilityCondition.swift | 82% | 86%
ReachableOperation.swift | 54% | 92%
Reachability.swift | 39% | 62%

Refactor ReachableOperation

---

Examples/Last Opened/Last Opened/AppDelegate.swift
Examples/Last Opened/Last Opened/ViewController.swift

This is some initial work to setup the Cloud Kit example. However there are some bugs which need to be ironed out before this can be fixed.
It will be a number of tickets/PRs before #169 is actually done.

[OPR-169]: Initial work on Cloud Kit example

---

Operations.xcodeproj/xcshareddata/xcschemes/OS X Operations.xcscheme
Operations.xcodeproj/xcshareddata/xcschemes/iOS Operations.xcscheme
Sources/Core/Shared/Operation.swift
Sources/Core/Shared/OperationCondition.swift
Tests/Core/AlertOperationTests.swift
Tests/Core/ComposedOperationTests.swift
Tests/Core/OperationTests.swift
Tests/Core/TimeoutObserverTests.swift
Tests/Features/CloudKitOperationTests.swift

This is an investigation of #175 which is a bug report indicating that completion blocks are not always called.

Investigating completion block not firing bug.

---

Examples/Permissions/Pods/SwiftyBeaver/README.md
Examples/Permissions/Pods/SwiftyBeaver/sources/BaseDestination.swift
Examples/Permissions/Pods/SwiftyBeaver/sources/ConsoleDestination.swift
Examples/Permissions/Pods/SwiftyBeaver/sources/FileDestination.swift
Examples/Permissions/Pods/SwiftyBeaver/sources/SwiftyBeaver.swift
Examples/Permissions/Pods/Target Support Files/SwiftyBeaver/Info.plist
Sources/Core/iOS/AlertOperation.swift
Sources/Core/iOS/UIOperation.swift
Tests/Core/AlertOperationTests.swift
Tests/Core/UIOperationTests.swift
examples/Permissions/Permissions/MainController.swift
examples/Permissions/Podfile.lock
examples/Permissions/Pods/Local Podspecs/Operations.podspec.json
examples/Permissions/Pods/Manifest.lock
examples/Permissions/Pods/Pods.xcodeproj/project.pbxproj
examples/Permissions/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Operations.xcscheme
examples/Permissions/Pods/Target Support Files/Operations/Info.plist

UIOperation does not always finish

---

Sources/Core/iOS/UIOperation.swift
Tests/Core/UIOperationTests.swift

Adds navigation controller wrapping overriding support to UIOperation #193

---

Sources/Core/Shared/ComposedOperation.swift
Sources/Core/Shared/GroupOperation.swift
Sources/Core/Shared/OperationQueue.swift
Sources/Features/Shared/CloudKitOperation.swift
Tests/Core/GroupOperationTests.swift
Tests/Features/CloudKitOperationTests.swift

Branch investigating errors within nested GroupOperation instances.

---

Operations.podspec
Operations.xcodeproj/project.pbxproj

CloudCapability should be available in tvOS

---

Tests/Core/OperationTests.swift

This was highlighted after #219 was reported.

Adds test to make sure that finished is called.

---

Sources/Core/Shared/Operation.swift
Sources/Core/iOS/BackgroundObserver.swift
Tests/Core/BackgroundObserverTests.swift

Reverts danthorpe/Operations#233

Revert "Make background task execution default on iOS"

---

Sources/Features/Shared/NetworkOperation.swift

Rebasing #255 onto `swift/2.1`

Pass network error if present when operation finishes

---

Operations.xcodeproj/project.pbxproj
Operations.xcodeproj/xcshareddata/xcschemes/iOS Operations.xcscheme
Sources/Core/Shared/GroupOperation.swift
Sources/Core/Shared/Operation.swift
Tests/Core/GroupOperationTests.swift
Tests/Core/OperationTests.swift
Tests/Core/RepeatedOperationTests.swift

This is to address issue #263.

Operation User Intent

---

.ci/scripts/test-ios
.swiftlint.yml
Sources/Core/Shared/BlockCondition.swift
Sources/Core/Shared/Operation.swift
Tests/Core/BlockConditionTests.swift

Support throwing block in BlockCondition

---

.gitignore

Add SPM support to .gitignore files

---

Sources/Features/iOS/LocationCapability.swift
Tests/Features/LocationCapabilityTests.swift

Bug #305 needs to be released for v2.10.0

CLLocationAuthorizationStatus bug

---

Sources/Core/Shared/ExclusivityManager.swift
Sources/Core/Shared/Operation.swift
Sources/Features/iOS/WebpageOperation.swift

This is to address questions in #287.

Improves cancellation checks in main()

---

Sources/Core/Shared/OperationQueue.swift
Sources/Core/iOS/AlertOperation.swift
Tests/Core/AlertOperationTests.swift

The AlertOperation now support 'addTextFieldWithConfigurationHandler(_:)'

Added missing functionality of UIAlertController to AlertOperation.

---

Sources/Core/Shared/RepeatedOperation.swift
Sources/Core/Shared/RetryOperation.swift
Sources/Features/Shared/CloudKit/CloudKitOperation.swift
Tests/Core/RepeatedOperationTests.swift
Tests/Core/RetryOperationTests.swift

RepeatedOperation allows for configuration block to be reset by the payload

---

Sources/Core/Shared/Condition.swift
Sources/Core/Shared/Operation.swift
Tests/Core/ConditionTests.swift

There is an error in the unit tests - and this isn't quite finished yet.

Fixes issue with Ignored condition results

---

Sources/Core/Shared/Operation.swift
Tests/Core/StressTests.swift

The potential existed for `Operation.cancelWithErrors()` to result in an assert due to an illegal state transition from `.Pending` =>`.Finishing` while `cancelled == false`.
This was fixed by ensuring that the additional cancellation errors are appended to the `_internalErrors` array at the same time that `_cancelled` is set to `true` (i.e. within the same acquisition of the lock).
Additionally, a StressTest of `Operation.cancelWithErrors()` was added.

Fix `Operation.cancelWithErrors()` thread-safety

---

Tests/Core/BasicTests.swift

This speeds up the test, and resolves possible main-thread-stall issues running the test.

Rewrite `test__dependent_operations_always_run` to use a dispatch_group instead of an expectation for every BlockOperation

---

Sources/Procedure.swift
Sources/ProcedureProcotol.swift

In _Operations_ v3 there is the concept of a `Result` which an `Operation` can conform to and produce.
This is used for `Condition` as its result is the `ConditionResult`.

Add Result

---

.ci/buildkite/pipeline.template.yml
ProcedureKit.xcodeproj/project.pbxproj
Sources/Collection+ProcedureKit.swift
Sources/Condition.swift
Sources/Errors.swift
Sources/Operation+ProcedureKit.swift
Sources/Procedure.swift
Sources/ProcedureProcotol.swift
Sources/ProcedureQueue.swift
Sources/Testing/StressTestCase.swift
Sources/Testing/TestCondition.swift
Sources/Testing/XCTAsserts.swift
Tests/ConditionTests.swift
Tests/Stress Tests/ProcedureStressTests.swift

Add Dependencies & Conditions

---

Sources/Extras/AddressBook/iOS/AddressBook.swift

CFErrorRef is a typealias for CFError that is a struct. Unmanaged is for objects only.wq
Updated PR for this discussion https://github.com/ProcedureKit/ProcedureKit/pull/451

Resolving Unmanaged<CFErrorRef> warning

---

Sources/BlockObservers.swift
Sources/Group.swift
Sources/Logging.swift
Sources/Support.swift

There are a bunch of escaping/non-escaping issues which need fixing now with Xcode 8 GM.

Fix Xcode 8 GM issues

---

ProcedureKit.xcodeproj/project.pbxproj
ProcedureKit.xcodeproj/xcshareddata/xcbaselines/653CA0171D60A34E0070B7A2.xcbaseline/6DA284CC-3922-4524-95E8-F180E4F487EF.plist
Sources/BlockProcedure.swift
Sources/Procedure.swift
Sources/Testing/StressTestCase.swift
Tests/BlockProcedureTests.swift
Tests/Stress Tests/BlockProcedureStressTests.swift
Tests/Stress Tests/GroupStressTests.swift
Tests/Stress Tests/ProcedureStressTests.swift

I want to re-visit the `BlockProcedure` API, as I don't really like how it works in _Operations_.

BlockProcedure

---

ProcedureKit.xcodeproj/project.pbxproj
Sources/Delay.swift
Sources/Testing/ProcedureKitTestCase.swift
Tests/DelayProcedureTests.swift

DelayProcedure

---

Sources/Core/Shared/Generators.swift
Sources/Core/Shared/RepeatedOperation.swift
Tests/Core/NetworkObserverTests.swift

Makes generators public

---

Sources/Core/Shared/Generators.swift
Sources/Core/Shared/RepeatedOperation.swift
Tests/Core/NetworkObserverTests.swift

Makes generators publicly accessible

---

ProcedureKit.xcodeproj/project.pbxproj
Sources/BlockObservers.swift
Sources/ProcedureObserver.swift
Tests/BlockObserverTests.swift
Tests/Stress Tests/ProcedureStressTests.swift

Add a fully customisable `BlockObserver`

BlockObserver

---

ProcedureKit.xcodeproj/project.pbxproj
Sources/BlockCondition.swift
Sources/Composed.swift
Tests/ComposedProcedureTests.swift

ComposedProcedure

---

ProcedureKit.xcodeproj/project.pbxproj
Sources/AnyObserver.swift
Sources/BlockCondition.swift
Sources/BlockObservers.swift
Sources/Capability.swift
Sources/Condition.swift
Sources/Errors.swift
Sources/MutualExclusion.swift
Sources/NegatedCondition.swift
Sources/NoFailedDependenciesCondition.swift
Sources/Procedure.swift
Sources/ProcedureObserver.swift
Sources/ProcedureProcotol.swift
Sources/ResultInjection.swift
Sources/Testing/CapabilityTestCase.swift
Sources/Testing/TestCondition.swift
Sources/Testing/XCTAsserts.swift
Tests/CapabilityTests.swift

The core `ProcedureKit` will support `CapabilityProtocol` and associated procedures for `Authorize` etc

CapabilityProtocol

---

Sources/Capability.swift
Sources/Testing/CapabilityTestCase.swift
Tests/CapabilityTests.swift

To address issues raised in #512.

Rename capability related procedures

---

Sources/ProcedureQueue.swift

Only added the will-do-something ones.

Adds default empty implementations some queue delegate methods

---

Sources/Collection+ProcedureKit.swift
Sources/Operation+ProcedureKit.swift
Sources/Testing/TestProcedure.swift
Tests/ProcedureTests.swift

Adds .then { } API

---

Tests/Stress Tests/BlockProcedureStressTests.swift

Cancel blocks frequently times out.

Improve stability of stress tests

---

Sources/Testing/ProcedureKitTestCase.swift

I'm going to cherry pick this commit: 3aa4ce1375b from #550, then rebase that branch.

Support waiting for an array of procedures

---

Sources/AnyObserver.swift
Sources/BlockObservers.swift
Sources/Procedure.swift
Sources/ProcedureObserver.swift
Tests/BlockObserverTests.swift
Tests/BlockProcedureTests.swift

As reported by @marek-rogosz-sky.

Add didExecuteObserver

---

Sources/Testing/GroupTestCase.swift
Tests/GroupTests.swift

- Add `GroupConcurrencyTestCase`
- Add `GroupProcedure.maxConcurrentOperationCount` tests

GroupProcedure concurrency tests

---

ProcedureKit.xcodeproj/project.pbxproj
Sources/Network/NetworkDownload.swift
Tests/Network/NetworkDownloadProcedureTests.swift

The implementation for class and test is largely inspired by
`NetworkDataProcedure` class.

Add NetworkDownloadProcedure.

---

ProcedureKit.xcodeproj/project.pbxproj
ProcessProcedureTests.swift
Sources/Mac/Process.swift

The class has been largely inspired by the original `TaskOperation`.
Refers to #568.

Add ProcessProcedure.

---

ProcedureKit.xcodeproj/project.pbxproj
Sources/AnyObserver.swift
Sources/BlockObservers.swift
Sources/Group.swift
Sources/Procedure.swift
Sources/ProcedureObserver.swift
Sources/ProcedureQueue.swift
Sources/Profiler.swift
Sources/Testing/ProcedureKitTestCase.swift
Tests/AnyProcedureTests.swift
Tests/BlockObserverTests.swift
Tests/GroupTests.swift
Tests/ProfilerTests.swift

Changes to address GroupProcedure observer bug

---

Sources/Capability.swift
Sources/Condition.swift
Sources/MutualExclusion.swift
Sources/NoFailedDependenciesCondition.swift
Sources/ProcedureQueue.swift
Tests/CapabilityTests.swift
Tests/MutualExclusivityTests.swift

Support Arbitrary mutual exclusion category names

---

Sources/Errors.swift
Sources/Procedure.swift
Sources/ProcedureProcotol.swift
Sources/ProcedureQueue.swift
Sources/Testing/TestProcedure.swift
Tests/GroupTests.swift
Tests/Mobile/NetworkObserverTests.swift

Test fails with:
`assertion failed: Attempting to perform illegal cyclic state transition, executing -> pending`

Producing operations from Group children fails

---

Sources/Repeat.swift
Sources/Support.swift
Sources/Testing/StressTestCase.swift

This prevents Release configuration builds.

Remove @testable import from TestingProcedureKit

---

ProcedureKit.xcodeproj/project.pbxproj
Tests/Stress Tests/RepeatStressTests.swift

(A similar test previously existed in Operations 3.x.)

Add RepeatProcedure cancellation stress test

---

Sources/Network/NetworkData.swift
Sources/Network/NetworkDownload.swift
Sources/Network/NetworkUpload.swift

Fixes copy/paste typos

---

Sources/Network/Network.swift
Tests/Network/NetworkProcedureTests.swift

Support result injection in NetworkProcedure

---

Sources/Repeat.swift
Tests/RepeatProcedureTests.swift

Support Repeatable types

---

README.md

Fixed typo in link to Dan's github profile

---

Sources/ProcedureKit/Any.swift
Tests/ProcedureKitTests/AnyProcedureTests.swift

This pull requests adds two classes: `AnyInputProcedure<Input>` and `AnyOutputProcedure<Output>`.
During implementation of this classes I replaced `AnyProcedureBox` with `ValueBox`.
Tests for procedures are the same as they were for `AnyProcedure`. Common code was moved to new `BaseAnyProcedureTests`.

AnyProcedure enhancements

---

.swiftlint.yml
Sources/ProcedureKit/Group.swift
Sources/ProcedureKit/MutualExclusion.swift
Sources/ProcedureKit/Procedure.swift
Sources/TestingProcedureKit/StressTestCase.swift

Update .swiftlint ruleset

---

Tests/ProcedureKitTests/BlockObserverTests.swift

Resolve a race condition in the test itself.

Robustness fixes for `test__did_add_synchronized`

---

README.md

Just made it more clear, I think.

Clarification for using Cocoapods

---

Guides/Basic Features/Groups.md

See: http://procedure.kit.run/feature/OPR-767_docs_groups/groups.html

Documentation guides - Groups

---

Guides/Basic Features/Groups.md
Guides/Cancellation/In Asynchronous Procedures.md
Sources/ProcedureKit/BlockObservers.swift
Sources/ProcedureKit/Composed.swift
Sources/ProcedureKit/Condition.swift
Sources/ProcedureKit/Group.swift
Sources/ProcedureKit/MutualExclusion.swift
Sources/ProcedureKit/NegatedCondition.swift
Sources/ProcedureKit/Procedure.swift
Sources/ProcedureKit/ProcedureEventQueue.swift
Sources/ProcedureKit/ProcedureObserver.swift
Sources/ProcedureKit/ProcedureQueue.swift
Sources/ProcedureKit/ProcedureResult.swift
Sources/ProcedureKit/Repeat.swift
Sources/ProcedureKit/Retry.swift
Sources/ProcedureKit/TimeoutObserver.swift

Improve documentation and Jazzy output via misc small fixes in the documentation.

Documentation tweaks and improvements

---

Sources/TestingProcedureKit/TestProcedure.swift

Previously, when `TestProcedure` was provided a `producedOperation`, it was possible for the `TestProcedure` to finish before the `producedOperation` was produced.
This resulted in occasional failures in certain tests, including:
`BlockObserverTests.test__did_add_operation_is_called()`
Also modified `TestProcedure` to no longer dispatch all of its internal blocks onto the main queue (unnecessary).

Fix race condition in TestProcedure

---

Sources/ProcedureKit/Procedure.swift
Tests/ProcedureKitStressTests/ProcedureStressTests.swift

Also fixes a rare race condition in which Conditions could begin to be evaluated prior to all of the parent Procedure’s dependencies finishing.

Simplify Procedure ConditionEvaluator state management

---

Sources/ProcedureKit/Group.swift

This is to get around Xcode 9 beta issues.

[OPR-765]: Removes final requirement

---

Sources/ProcedureKitLocation/ReverseGeocodeUserLocation.swift

[OPR-790]: Makes ReverseGeocodeUserLocation init public

---

ProcedureKit.podspec
Supporting Files/ProcedureKit.xcconfig

Breaking change as part of Xcode 9

Updates to minimum of watchOS 3

---

Sources/ProcedureKitNetwork/NetworkData.swift
Sources/ProcedureKitNetwork/NetworkDownload.swift
Sources/ProcedureKitNetwork/NetworkSupport.swift
Sources/ProcedureKitNetwork/NetworkUpload.swift
Tests/ProcedureKitNetworkTests/NetworkDataProcedureTests.swift
Tests/ProcedureKitNetworkTests/NetworkDownloadProcedureTests.swift
Tests/ProcedureKitNetworkTests/NetworkProcedureTests.swift
Tests/ProcedureKitNetworkTests/NetworkUploadProcedureTests.swift
Tests/ProcedureKitNetworkTests/ProcedureKitNetworkTests.swift

See #814 for the original issue.
Cherry picked commit: https://github.com/ericyanush/ProcedureKit/commit/11a7873b5f4822e281048a7c56287264e4e139fc

Remove associated types from Network

---

Package.swift

See https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV4.md

Update Package.swift to v4 definition

---

Sources/ProcedureKit/Block.swift

Removes a strong reference to self.

Fixes potential memory leak

---

Sources/ProcedureKit/Block.swift

Adds a simple `UIBlockProcedure` to make it easier to add operation which perform UI stuff on the main thread. This is a little bit of a hack to just execute the block inside another operation on the main queue though, so could be done by adding the procedure to the queue directly.

UIBlockProcedure

---

Sources/ProcedureKitMobile/ViewControllerContainment.swift

There are some annoying API inconsistencies here.

Fix minor issues with UIViewControllerContainment procedures

---

Sources/ProcedureKit/Delay.swift
Tests/ProcedureKitTests/DelayProcedureTests.swift

This will allow for injecting the delay as calculated from another (Output)Procedure into DelayProcedure.

Supports InputProcedure on DelayProcedure

---

Sources/ProcedureKit/ProcedureResult.swift
Tests/ProcedureKitTests/ResultInjectionTests.swift

Fixes retain cycle due to strong self capture in inject result

---

Sources/ProcedureKit/ProcedureEventQueue.swift

Made public makeTimerSource
Second PR, here is discussion: https://github.com/ProcedureKit/ProcedureKit/issues/892

Make public makeTimerSource API

---

Sources/ProcedureKit/Result.swift
Tests/ProcedureKitTests/BlockProcedureTests.swift

To resolve issues raised by #900.

ResultProcedure init fixes

---

ProcedureKit.podspec
Sources/ProcedureKitCloud/Record Operations/CKFetchDatabaseChangesOperation.swift
Tests/ProcedureKitCloudTests/CKDiscoverAllUserIdentitiesOperationTests.swift
Tests/ProcedureKitCloudTests/CKDiscoverUserIdentitiesOperationTests.swift
Tests/ProcedureKitCloudTests/CKFetchDatabaseChangesOperationTests.swift
Tests/ProcedureKitCloudTests/CKFetchNotificationChangesOperationTests.swift
Tests/ProcedureKitCloudTests/CKFetchRecordZoneChangesOperationTests.swift
Tests/ProcedureKitCloudTests/CKFetchRecordsOperationTests.swift
Tests/ProcedureKitCloudTests/CKFetchShareParticipantsOperationTests.swift
Tests/ProcedureKitCloudTests/CKModifyRecordsOperationTests.swift

Further fixes for CloudKit

---

ProcedureKit.xcodeproj/project.pbxproj
Sources/ProcedureKit/Decode.swift
Sources/ProcedureKit/Encode.swift
Tests/ProcedureKitTests/JSONCodingTests.swift

JSON Coding procedures
