framework/Operations/Operations/Operation.swift

Currently, any subclass of `Operation` can't call produceOperation as it's private to `Operation`

Make produceOperation public

---

framework/Operations/Conditions/Permissions/CloudCondition.swift
framework/Operations/Queue/ExclusivityManager.swift
framework/OperationsTests/CloudConditionTests.swift
framework/OperationsTests/OperationsTests.swift

If the use is not logged in, the error returned from CloudKit is nil, but the status is `.NotSet`.

Improve the cloud condition errors.

---

framework/Operations.xcodeproj/project.pbxproj
framework/Operations/Conditions/ReachabilityCondition.swift
framework/Operations/Operations/ReachableOperation.swift
framework/OperationsTests/ReachabilityConditionTests.swift
framework/OperationsTests/ReachableOperationTests.swift

While `ReachableCondition` will fail an operation if the network is not available, we also want a way to be able to run an operation when the network comes back.

Support a ReachableOperation

---

framework/Operations.xcodeproj/project.pbxproj
framework/Operations/Conditions/UserConfirmationCondition.swift

It's a fairly common requirement to get the user to confirm a destructive, or potentially destructive action. E.g. we ask the use if they're sure they want to delete a resource before we just do it.
So... here we want an `UserConfirmationCondition` which can be initialised with a title, message and action title and it will present an alert (to this effect) and if the user taps in the affirmative, the operation will run.

User confirmation alert condition.

---

Operations/Operations/GroupOperation.swift
OperationsTests/GroupOperationTests.swift

It is possible to achieve a deadlock through the use of mutually exclusive conditions (such as alert) and group operations.
When a group operation has a child operation which has a mutually exclusive condition. Adding a condition with the same mutual exclusivity condition type to the group will create a deadlock. This is because the child's condition is added first to the exclusivity manager, and so the group condition will never evaluate. This stops the group from executing, and the child relinquishing it's lock on that mutually exclusive condition.
A simple workaround is to either
1. If you're adding the group's condition inside the group itself, then you can add the child operations during it's `execute` method.
2. If you're adding the group's condition outside of the group, you will …

Possible to create a deadlock using mutual exclusive conditions and group operations.

---

Operations/Operations/GroupOperation.swift
Operations/Operations/Operation.swift
Operations/Queue/OperationQueue.swift
OperationsTests/CalendarConditionTests.swift
OperationsTests/ReachableOperationTests.swift

I've modified 'unused map result' warnings to use foreach syntax in order to improve efficiency a bit. Other option was to silence the warning by adding '_ =' prefix, but I thought that was worse.

Fix compilation and warnings on Xcode7b6.

---

Operations/Operations/GroupOperation.swift
Operations/Operations/Operation.swift
OperationsTests/NoCancelledConditionTests.swift

I think the intention for NoCancelledCondition was to cancel the dependencies when an operation either cancels or finishes with an error. But current implementation works only for explicit cancellations.
If my reading of the NoCancelledCondition intent was incorrect, then I need to add NoFailedCondition, and somehow check that dependent operations finished without having any errors, but there's no way to check for that: the easiest way to solve this would be to add `var errors: [ErrorType] { get { _internalErrors }}` property.

Cancel Operation when it finishes with an error.

---

Operations.xcodeproj/project.pbxproj
Operations/Conditions/NoFailedDependenciesCondition.swift
Operations/Operations/Operation.swift
Operations/Support.swift
OperationsTests/NoFailedDependenciesConditionTests.swift

Also there is a slight bug in how `Operation` evaluates readiness, which should be sorted. Also, I'm thinking that the internal `State` should be made thread safe...

Update Swift 1.2 with recent changes in Swift 2.0

---

Operations.xcodeproj/project.pbxproj
OperationsTests/OperationTests.swift
OperationsTests/ReachableOperationTests.swift

Most test operations have execution times of a second. Taking that there are many tests, the whole suite as a whole takes too long to run.
I think it would be possible to make most of them instant (0-second delay), and for those that rely on timers make intervals very small (`0.01` second should be fine, I think).

Tests take too long to finish

---

Operations/Queue/OperationQueue.swift
OperationsTests/MutualExclusiveTests.swift

Fix mutual exclusivity

---

Operations.podspec
Operations.xcodeproj/project.pbxproj
Operations/Core/Shared/LoggingObserver.swift
Operations/Extras/AddressBook/iOS/AddressBookOperations.swift
Operations/Extras/AddressBook/iOS/AddressBookUIOperations.swift
Operations/Extras/Contacts/Shared/ContactsCondition.swift
Operations/Extras/Contacts/Shared/ContactsOperation.swift
Operations/Extras/Contacts/iOS/ContactsUIOperations.swift
OperationsTests/Core/LoggingObserverTests.swift
OperationsTests/Extras/Contacts/ContactsOperationsTests.swift

Support use of Contacts framework (across all appropriate platforms)

Contacts #1

---

Operations/Features/Shared/Capability.swift
Operations/Features/Shared/CloudCapability.swift
Operations/Features/iOS/UserNotificationCondition.swift

This is the most tricky one as it's asynchronous - but also, the capability should expose access to it's underlying `CKContainer`.

Improve Cloud Capability

---

.gitignore
Operations.xcodeproj/project.pbxproj
Operations/Core/Shared/BlockCondition.swift
Operations/Core/Shared/BlockObserver.swift
Operations/Core/Shared/BlockOperation.swift
Operations/Core/Shared/ComposedOperation.swift
Operations/Core/Shared/DelayOperation.swift
Operations/Core/Shared/ExclusivityManager.swift
Operations/Core/Shared/GatedOperation.swift
Operations/Core/Shared/GroupOperation.swift
Operations/Core/Shared/LoggingObserver.swift
Operations/Core/Shared/MutuallyExclusive.swift
Operations/Core/Shared/NegatedCondition.swift
Operations/Core/Shared/NoFailedDependenciesCondition.swift
Operations/Core/Shared/Operation.swift
Operations/Core/Shared/OperationCondition.swift
Operations/Core/Shared/OperationObserver.swift
Operations/Core/Shared/OperationQueue.swift
Operations/Core/Shared/SlientCondition.swift
Operations/Core/Shared/Support.swift
Operations/Core/Shared/TimeoutObserver.swift
Operations/Core/iOS/AlertOperation.swift
Operations/Core/iOS/BackgroundObserver.swift
Operations/Core/iOS/NetworkObserver.swift
Operations/Core/iOS/UIOperation.swift
OperationsTests/Core/SilentConditionTests.swift

Documentation in the source code is pretty dismal - less than 10%. So, will aim to fix that in a number of tickets for 2.3 release.
In this ticket...
In future tickets...

Documentation Blitz

---

Operations/Features/Shared/Reachability.swift
Operations/Features/Shared/ReachableOperation.swift

There is a subtle bug with `ReachableOperation`, which can result in the composed operation not executing even though the network is reachable.
The scenario is simply that the first time a `ReachableOperation` is executed, it will setup it's fire mechanism with no reachable flags. Therefore - there is a change, and all observers are notified.
However, if you then create another `ReachableOperation` - the system reachability object begin executing again (as there is a new observer) - however the flags are known - so if there isn't any change, they won't fire, and the new observer will not be notified.

Bug with ReachableOperation

---

Operations/Core/Shared/Operation.swift
OperationsTests/Core/OperationTests.swift

In the process of implementing a logout handler for a special operation queue I use for all of my network operations, I've become confused as to what the proper cancellation behavior should be for `Operation` subclasses. For context, this is my `NetworkOperation` that wraps an Alamofire `Request`:
```swift
class NetworkOperation<T: Decodable where T == T.DecodedType> : Operation {
let request: Request
var completionHandler: ((T?, APIError?) -> Void)? = nil
init(request: Request) {
self.request = request
super.init()
request.responseObject { (responseObject: T?, error: APIError?) in
if let error = error where error.isInvalidTokenError {
self.finish(error)
}
else {
self.completionHandler?(responseObject, error)
self.finish(error)
}
}
addObserver(NetworkObserver()) …
```

Proper cancellation?

---

Operations/Features/iOS/LocationOperations.swift
OperationsTests/Features/LocationOperationsTests.swift

The Location operations seem to be the most unreliable.

Test Coverage Blitz - Fix some unreliable tests

---

Sources/Features/iOS/RemoteNotificationCondition.swift

The two notification names conflict, which cause unexpected notification handling when RemoteNotificationsRegistration and UserNotificationPermissionOperation are used simultaneously.

RemoteNotificationName conflicts DidRegisterSettingsNotificationName

---

Sources/Core/Shared/Operation.swift

From following the Swift evolution mailing list, there has been some clarifications regarding the usage of `assert` and `precondition`. There are definitely improvements that we need here. `addObserver`, `addDependency` etc should be using precondition with clearer documentation about the expected state.

Improve clarity of Operation public API

---

Sources/Features/iOS/LocationOperations.swift
Tests/Features/LocationOperationsTests.swift

Conform to ResultOperationType where appropriate

---

README.md

Definitely need to update the README to help people understand what Operations is all about. Off the top of my head, these are the things which need improving or better guidance.

Update README & Wiki

---

Operations.xcodeproj/project.pbxproj
Sources/Core/Shared/ComposedOperation.swift
Sources/Core/Shared/GroupOperation.swift
Sources/Core/Shared/Operation.swift
Sources/Core/Shared/RepeatedOperation.swift
Sources/Core/Shared/RetryOperation.swift
Sources/Features/Shared/ReachableOperation.swift
Tests/Core/RepeatedOperationTests.swift
Tests/Core/RetryOperationTests.swift

Here are my thoughts on a possible `RetryOperation`.
1. It would be a way of reliably executing an operation which can "fail" (finish with errors).
2. It would be a little bit like `ReachableOperation` / `ComposedOperation` where the target operation is composed inside a group operation.
3. The target operation gets a `NoFailedDependenciesCondition` added
4. If the target operation finishes with any errors, another instance of the same operation is added to the group after a delay
5. When creating the `RetryOperation`, the initializer should accept a (minimum) time delay, a flag for whether the delay should be exponentially backed-off (is that a term?).
6. Perhaps also define a maximum number of attempts - but default to `.None`.
It might also be useful to architecture this as a subclass …

Retry Operation

---

Sources/Core/Shared/Operation.swift
Sources/Core/Shared/OperationQueue.swift
Tests/Core/OperationTests.swift
Tests/Core/RepeatedOperationTests.swift
Tests/Features/LocationOperationsTests.swift

This PR implements the changes as discussed in #147. Essentially each `Operation` instance now has an internal optional `NSOperation` property. This property is simply a *waiter*, and serves no purpose other than for dependency management.
We also now have the concept of *direct dependency* (or maybe regular dependency), and an *indirect dependency*. A direct dependency is one added via `addDependency` whereas an indirect dependency is the dependency of an operation condition.
When `addDependency` is invoked, the argument operation is added as a dependency to an internal `NSOperation` instance which is created on the fly (and added as a dependency of the receiver using `super.addDependency`). Essentially this creates a dummy operation which acts as a surrogate for the receiver. It waits …

Operations from conditions execute after the operation's dependencies

---

Sources/Core/Shared/RepeatedOperation.swift
Sources/Core/Shared/RetryOperation.swift
Tests/Core/RetryOperationTests.swift

At the moment, `RepeatedOperation` is sort of like a signal producer - it just keeps on scheduling operations as long as the generator returns them, with various delays in between.
`RetryOperation` is the same except that it will finish as soon as an operation succeeds.
I'm going to change `RetryOperation` so that it's finishing does not only depend on whether the operation succeeds, but also whether or not the consumer wants to try again (or not). This should support last operation, latest errors, aggregate errors.
This is also to support Phase Two of #160.

Refactor RetryOperation

---

Sources/Core/Shared/ComposedOperation.swift
Sources/Core/Shared/GatedOperation.swift
Tests/Core/ComposedOperationTests.swift
Tests/Core/GatedOperationTests.swift

These two operations which are not used very much, and I want to tweak them to fix a few issues. The main idea behind `ComposedOperation` is that other `NSOperation` instances can be wrapped in an `Operation`. `GatedOperation` is the same, except it runs a block at execution which determines whether the composed operation is added to the queue.
If the composed operation is a subclass of `NSOperation` but not `Operation` then we *must* run it inside a group. However, if it is an `Operation` subclass, then we can use `produceOperation` and observers and not use a group. So, this logic should all be internal to `ComposedOperation`. `GatedOperation` is just a simple subclass of `ComposedOperation` (at the moment, it's the other way around).
Once this is all fixed, then things like …

Refactor ComposedOperation & GatedOperation

---

.gitignore
Examples/Last Opened/Last Opened.xcodeproj/project.pbxproj
Examples/Last Opened/Last Opened.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Examples/Last Opened/Last Opened.xcworkspace/contents.xcworkspacedata
Examples/Last Opened/Last Opened/AppDelegate.swift
Examples/Last Opened/Last Opened/Assets.xcassets/AppIcon.appiconset/Contents.json
Examples/Last Opened/Last Opened/Base.lproj/LaunchScreen.storyboard
Examples/Last Opened/Last Opened/Base.lproj/Main.storyboard
Examples/Last Opened/Last Opened/Info.plist
Examples/Last Opened/Last Opened/ViewController.swift
Examples/Last Opened/Podfile
Examples/Last Opened/Podfile.lock
Sources/Core/Shared/ComposedOperation.swift
Sources/Core/Shared/GatedOperation.swift
Sources/Core/Shared/GroupOperation.swift
Sources/Core/Shared/Operation.swift
Sources/Features/Shared/CloudKitOperation.swift
Sources/Features/Shared/ReachableOperation.swift
Tests/Core/ComposedOperationTests.swift
Tests/Core/GatedOperationTests.swift
Tests/Core/GroupOperationTests.swift
Tests/Features/CloudKitOperationTests.swift
Tests/Features/ReachableOperationTests.swift

Refactor `ReachableOperation`, to subclass `ComposedOperation`, and then `CloudKitOperation` should subclass `ReachableOperation`.
Given this, the `ReachableOperation` will manage errors/executing the operation when the app is online.
Execution inside of a `RetryOperation` will support errors/executing the operation in the face of errors from CloudKit. Which leaves `CloudKitOperation` to support the configuration of the underlying target operation.
It seems a bit silly that consumers should be adding an `AutorizedFor(Capability.Cloud())` condition to their `CloudKitOperation` instances. Instead, it might make sense to support initializing `CloudKitOperation` with permissions (with a default) and a container id (with a default). This way, we can automatically add a condition.
- ~~[ ] …

Refactor CloudKitOperation, phase 3

---

Sources/Core/Shared/DelayOperation.swift
Sources/Core/Shared/RepeatedOperation.swift
Sources/Core/Shared/RetryOperation.swift
Tests/Core/RepeatedOperationTests.swift
Tests/Core/RetryOperationTests.swift

At the moment, `RepeatedOperation` uses two generators, one for delays and another for the operation, which in hindsight is a little bit limiting.
A better approach would be a generator of type `(NSTimeInternal?, T)` or `(NSDate?, T)`... so that the generator can be responsible for injecting it's own delay.
Another factor would be how to take latest and aggregate errors into account.

Refactor RepeatedOperation & RetryOperation

---

Sources/Core/iOS/UIOperation.swift
Sources/Features/iOS/WebpageOperation.swift
Tests/Core/UIOperationTests.swift

`UIOperation` does not actually finish after it does the presentation. But it does accept a completion block. This is all a bit strange. There is no need for a completion block, and instead, it should just `finish()`.

UIOperation does not finish

---

Sources/Core/Shared/Operation.swift

Calling produceOperation without being on a OperationQueue will silently fail. If you try to use produceOperation in an operation initializer this situation might happen.

Adding precondition to produceOperation method

---

Operations.xcodeproj/project.pbxproj
Operations_ExtensionCompatible.xcodeproj/project.pbxproj
Sources/Core/Shared/GroupOperation.swift
Sources/Core/Shared/OperationQueue.swift
Sources/Core/Shared/ThreadSafety.swift
Tests/Core/GroupOperationTests.swift

This is to address the issue raised by @ansf in #181.
The basic issue is that the `aggregateErrors` property of `GroupOperation` is not thread safe. We do not need to create a huge group of operations to show this, just 10 will do it, and check that when the group finishes the number of errors is as expected.
This also highlights another issue with how the tests are often written. We add a `FinishedObserver` to the operation which is being tested. In it's block we fulfill the expectation. Then we wait for the expectations. The problem with this approach, is that the `FinishedObserver` is called as the `Operation` transitions from `.Finishing` to `.Finished` - so it's not *actually* finished. The reason it works like this, is so that it is possible to use the block to keep the operation …

Investigating bug/crash in GroupOperation #181

---

.ci/buildkite/pipeline.template.yml
Sources/Features/Shared/Reachability.swift
Sources/Features/Shared/ReachableOperation.swift
Tests/Features/ReachabilityTests.swift

There is still a bug in `ReachableOperation`. It works correctly when the device is already online, however when offline, the operation does not execute when the device comes back online.
The most recent change here remove the private singleton which was holding all the "observers" instead making them all individual. But this is not going to work.
So, back to the drawing board and need to re-consider how this can be unit tested. Possibly move away from the function registered in the run loop - as it's hard to make this non-global.

Reachable Operation - still has a bug

---

Sources/Core/Shared/BlockObserver.swift
Sources/Core/Shared/ComposedOperation.swift
Sources/Core/Shared/ExclusivityManager.swift
Sources/Core/Shared/GroupOperation.swift
Sources/Core/Shared/LoggingObserver.swift
Sources/Core/Shared/Operation.swift
Sources/Core/Shared/OperationObserver.swift
Sources/Core/Shared/OperationQueue.swift
Sources/Core/Shared/RepeatedOperation.swift
Sources/Core/Shared/ResultInjection.swift
Sources/Core/Shared/RetryOperation.swift
Sources/Core/Shared/TimeoutObserver.swift
Sources/Core/iOS/BackgroundObserver.swift
Sources/Core/iOS/NetworkObserver.swift
Sources/Extras/AddressBook/iOS/AddressBookUIOperations.swift
Sources/Extras/Contacts/iOS/ContactsUIOperations.swift
Sources/Features/Shared/CloudKitOperation.swift
Sources/Features/iOS/LocationOperations.swift
Sources/Features/iOS/UserConfirmationCondition.swift
Tests/Core/BlockConditionTests.swift
Tests/Core/BlockObserverTests.swift
Tests/Core/LoggingObserverTests.swift
Tests/Core/NegatedConditionTests.swift
Tests/Core/OperationTests.swift
Tests/Core/RepeatedOperationTests.swift
Tests/Core/TimeoutObserverTests.swift
Tests/Extras/AddressBook/AddressBookConditionTests.swift
Tests/Features/LocationOperationsTests.swift
Tests/Features/RemoteNotificationConditionTests.swift
Tests/Features/UserNotificationConditionTests.swift

This is to address the points raised in #152 by @jshier. Plus a few things I've noticed subsequently while fixing bugs for v2.6.
The reasoning behind this, is that typically, observers want to know when the operation did *actually* finish. This means that `XCTAssertTrue(operation.finished)` should pass. However... `GroupOperation` and its like, will often want to use this observer (or a similar event) to add new operations to the queue. Hence, it used to be posted before the state change. Now, we just have two observers, one before and one after.
For example, instead of `operationDidStart` it is `didStartOperation`. Changed consistently throughout including in `GroupOperation`, which now provides `willFinishOperation` instead of `operationDidFinish` - note that this takes the change above …

Refactor Observers

---

Sources/Core/Shared/BlockObserver.swift
Sources/Core/Shared/LoggingObserver.swift
Sources/Core/Shared/OperationObserver.swift
Sources/Core/iOS/NetworkObserver.swift
Tests/Core/BlockObserverTests.swift
Tests/Core/GroupOperationTests.swift

~~- [ ] Add `willDetachFromOperation` to the base protocol~~ - This is actually a little bit harder to figure out. Probably not worth the extra blocking calls to remove the observers. Especially as we'd have to figure out which ones are safe to remove.
~~- [ ] Prune observers from the `Operation` after their last event has been observed.~~
~~- [ ] Add property for `willDetach` to all the block based observers.~~

Refactor Observers, part 2

---

Sources/Core/Shared/BlockObserver.swift
Sources/Core/Shared/LoggingObserver.swift
Sources/Core/Shared/OperationObserver.swift
Sources/Core/iOS/NetworkObserver.swift

Essentially, this got left in here from previous work, it's not used yet. Should be made correct, then removes.

Refactoring Operation Observers, part 3

---

Sources/Core/Shared/RepeatedOperation.swift
Sources/Core/Shared/RetryOperation.swift
Tests/Core/RepeatedOperationTests.swift
Tests/Core/RetryOperationTests.swift

At the moment, it's very tricky to subclass `RepeatedOperation` from outside the module.
This is to address issues raised in #199.

Refactor RepeatedOperation initializers

---

Operations.podspec

Hi there,
Great lib! We're just starting using this, and noticed that in spite of the current use of subspecs, it would be nice to make them just a shade more granular. In particular, we'd rather not CloudKit unnecessarily, which is currently required in the Standard subspec.
In any case, please let me know what you think.
Thanks!

Make podspec dependencies more granular

---

Sources/Core/Shared/ResultInjection.swift

Hi there,
Courtesy of @estromlund. These appear to be retain cycles; the `previous` operation is added as a dependency of the `subsequent` operation, but the block retains the `subsequent` operation, so we would seem to have a clear retain cycle. Certainly adding this fixed some cycles for us. Please let us know if you think we might be using things incorrectly.
Thanks!

Fix suspected retain cycles in result injection

---

Sources/Features/Shared/ReachabilityCondition.swift
Tests/Features/ReachabilityConditionTests.swift

Originally https://github.com/danthorpe/Operations/pull/208
Sorry for the noise. Turns out we *do* still need to do something, since we need to store properties. Another solution, which I suspect you won't like!, is to make the `reachability` property into an (internal) var, defaulting to `ReachabilityManager(DeviceReachability())`, and remove it from the initializer entirely. This is still testable, by setting the var.
Not super elegant, but I think this solves our immediate need. Please let me know what you think.
Thanks!

Move HostReachabilityType dependency to a var, to allow for subclassing

---

Sources/Features/Shared/ReachabilityCondition.swift
Tests/Features/ReachabilityConditionTests.swift

Hi, again!
So another change related to the feature mentioned in https://github.com/danthorpe/Operations/pull/209: As stated there, we implement a `ReachabilityCondition` for WiFi only. We then test for throttling, and possibly have another condition for WWAN only.
In any case, I noticed that the pattern matching doesn't appear to accept the case where we want Wifi only, and only wifi is available. I think this is based on the idea that in the real world, we're more likely to have WWAN, although WiFi is higher priority. In any case, added this as a succeeding condition, including a test.
Not sure this is the most elegant matching, either: I don't claim to be the greatest Swift-er (yet!).
Please let me know what  you think.
Thanks!

Reachabiility should pass when constrained to wifi only, and wifi is available

---

Sources/Features/Shared/CloudKitOperation.swift
Sources/Features/Shared/ReachableOperation.swift
Tests/Features/CloudKitOperationTests.swift
Tests/Features/ReachabilityConditionTests.swift
Tests/Features/ReachableOperationTests.swift

Having merged some PRs, `development` is currently broken - and in general, the reachability stuff needs a bit of TLC.

Remove Reachability from initializer in ReachableOperation

---

Sources/Core/Shared/GroupOperation.swift
Sources/Core/Shared/Operation.swift

Hi again ;)
A minor one: previously using `verbose` for all logging, which means that genuine error cases can get lost in a verbose log (currently we're looking at everything). Changed to `warning` for when there are errors. With coloured output this should mean that errors don't get lost in the log.
Subjective of course. Let us know what you think.

Use log.warning for all error cases

---

Sources/Core/Shared/ResultInjection.swift

When injecting results using a `DidFinishObserver`, there is a race condition when the dependent operation becomes ready and executes *after* its dependency finishes but *before* the dependency's `DidFinishObserver` is triggered. This means the dependent operation occasionally executes before its dependency's result is injected and fails due to a missing `requirement`.
Switching this to a `WillFinishObserver` ensures that the result is injected before the dependency finishes, and before the dependent operation is allowed to execute.

Inject results with WillFinishObserver to avoid race condition

---

Sources/Core/Shared/Operation.swift
Sources/Core/iOS/BackgroundObserver.swift
Tests/Core/BackgroundObserverTests.swift

Make background task execution default on iOS

---

Sources/Core/Shared/GroupOperation.swift
Tests/Core/GroupOperationTests.swift

Currently, there's a race condition in `GroupOperation` when cancelling. Since the group first cancels its composing operations before setting its own `_cancelled` flag, sometimes the internal queue will finish and the group operation will finish before `super.cancel()` is run, resulting in the `_cancelled` flag never being set.
Look at 431dd07 for a test proving the race condition exists by inserting a sleep between `queue.cancelAllOperations` and `super.cancel()`
This PR remedies the problem by calling `super` first and setting the groups own state before cancelling its children.

Fix race condition when cancelling group operation

---

Sources/Core/iOS/AlertOperation.swift

Is there a reason why it needed to be the other way around?
Currently I have a `GroupOperation` where the `AlertOperation` is the only one created at startup. Then depending on the option selected by the alert I add another operation to the group. 
However because finish is called before the alert handler, I get an error saying I can't add an operation to the group after it has finished

Finish AlertOperation after call to handler

---

Sources/Core/Shared/BlockObserver.swift
Sources/Core/Shared/GroupOperation.swift
Tests/Core/GroupOperationTests.swift

`GroupOperation` will inform an observer when new operations are going to be added to its queue. This would be a direct reflection of the `OperationQueueDelegate`, but it can be used like a regular observer.

Support will add child operation observer in GroupOperation

---

Operations.xcodeproj/project.pbxproj
Sources/Core/Shared/Logging.swift
Sources/Core/Shared/Operation.swift
Sources/Core/Shared/OperationObserver.swift
Sources/Core/Shared/Profiler.swift
Sources/Core/Shared/ThreadSafety.swift
Tests/Core/ProfilerTests.swift

This is an idea prompted by some stuff done by @itsthejb in his fork.
The aim is to provide a way to extract performance metrics from `Operation` instances in a way which is amenable to feeding into analytics and tooling. The purpose for this might be to provide end-to-end integration metrics or for full system diagnostics, or even just to set some idea of the performance of a particular `Operation`.
Now, I hasten to add, that there is a strong argument that shipping apps should not include any kind of performance metrics code. The flip side of the coin, especially if you have an app which is getting 10k-100k or more DAUs is that it is very tricky to diagnose performance problems across all of your user's environments. From different devices, to networks, carriers and countless others. …

Operation Profiler

---

Sources/Core/Shared/GroupOperation.swift

Again, is there a reason it needs to be the other way around?
I have an instance where after one group operation finishes I need to look at the results of that group's child operations.
If the group operation is cancelled before the children, it finishes before the children have a chance to cancel and update their status.

Cancel Group Operation after cancelling Child Operations

---

Sources/Core/iOS/AlertOperation.swift
Tests/Core/AlertOperationTests.swift

I'd like to be able to use alert operation for showing an ActionSheet as well:
`let alertOp = AlertOperation(presentAlertFrom: self, style: .ActionSheet)`

Add preferredStyle to AlertOperation initializer

---

Sources/Features/iOS/PhotosCapability.swift
Tests/Features/PhotosCapabilityTests.swift

This was not getting trigged in unit tests, because the registrar property is lazy. And for all tests we replace the actual registrar object (in this case the PHPhotoLibrary) with a testable equivalent.
This means that the init() of PHPhotoLibrary was never called - and it turns out that it hits a run time exception.
This is exactly the sort of bug that Swift prevents, as if PHPhotoLibrary were written in Swift, the code would not have even compiled.
This fixes #280.

Fixes bug accessing the PHPhotoLibrary

---

.ci/scripts/test-ios

I just don't understand how reporting code coverage can be so error prone! At the moment @codecov only reports the coverage for the diffs in the branch - not the total coverage.

Removes Codecov

---

Operations.xcodeproj/project.pbxproj

- WatchOS target wasn't building due to CloudKit references.

- Un-ticking target for watchOS CloudKit references

---

Sources/Core/Shared/Operation.swift

`finished` has been renamed to `operationDidFinish` but the `@availability` attribute did not reflect this.
This fixes #299.

Fix an incorrect Xcode Fix-It hint.

---

Sources/Core/Shared/Operation.swift

There are some logs in `Operation` which are incorrectly using `.Notice` log severity.

Logs using notice severity

---

Sources/Features/iOS/LocationCapability.swift

I'm not sure why it thinks this is the right thing to do, but in some (but perhaps not all?) cases when asking CLLocationManager to authorize us for Location updates, it will immediately respond with 'NotDetermined' and then show the user the dialog asking for permission. After the dialog is dismissed, it proceeds to call us back with the proper status value.
Without this fix, adding a condition like this: 
addCondition(AuthorizedFor(Capability.Location()))
will immediately fail our operation due to the premature callback.

Creating a UI which reflects CLLocationAuthorizationStatus

---

Sources/Features/iOS/WebpageOperation.swift

Extended WebpageOperation with the ability to configure entersReaderIfAvailable at initialization.
It is possible now to show an SFSafariViewController with entersReaderIfAvailable set to false.

WebpageOperation support for entersReaderIfAvailable

---

Sources/Features/iOS/WebpageOperation.swift
Tests/Features/WebpageOperationTests.swift

I notices that WebpageOperation has an retain cycle in its current implementation.
I changed it to be a GroupOperation, because it actually is even if it only has one UIOperation.
Added a WillExecuteObsersever to setup the delegate property of SFSafariViewController.

Bugfix: Retaincycle in WebpageOperation 

---

Sources/Core/Shared/Condition.swift

Since refactoring `OperationCondition` into `Condition` which is an `Operation` subclass, there is now an issue where any condition dependencies are executed immediately (well upon adding to the queue), which is not the desired behaviour.

Error when removing condition dependencies

---

Sources/Core/Shared/Logging.swift

This allows me to pass around logging levels within a project that is mainly Objective-C.

Expose LogSeverity enum to objective-c

---

.gitignore
Sources/Core/Shared/TimeoutObserver.swift
Sources/Features/Shared/CloudKit/CloudKitOperation.swift
Tests/Features/CloudKitOperationTests.swift

Instead add a `TimeoutObserver` with a default timeout. As mentioned in #294.

Remove Reachability from CloudKitOperation

---

Sources/Core/Shared/Operation.swift

This fixes #339.
I've tested it inside my own project to make sure it is accessible to Objective-C code. Wasn't sure how to write a test in that since this project is just Swift.

Made UserIntent enum objc accessbile

---

Sources/Core/iOS/NetworkObserver.swift
Tests/Core/NetworkObserverTests.swift

Added tests for **multiple** operations having network observers.
Fixes #335 
I'm not 100% a fan of this implementation. This biggest change here is simply having tests in place that make sure that `networkActivityIndicatorVisible` doesn't get set multiple times unless it is a change in value.
Please feel free to give pointers on what I can do to improve this. I really appreciated seeing the way these tests were originally setup, nicely done. I'll add some questions in the code itself to get a better understanding.
I could reduce the number of methods or override a setter in the controller which manages changing `networkActivityIndicatorVisible` based on if it is a new value, but I'm not sure that provides any better readability.
@danthorpe mentioned in #335 that reducing the methods …

Network observer flickering

---

Operations.xcodeproj/project.pbxproj
Operations_ExtensionCompatible.xcodeproj/project.pbxproj
Sources/Core/Shared/Queue.swift
Sources/Core/Shared/Support.swift
Sources/Core/Shared/ThreadSafety.swift
Sources/Features/iOS/LocationCapability.swift
Sources/Features/iOS/LocationOperations.swift
Tests/Features/LocationOperationsTests.swift

Me again with another CLLocationManager bug/issue/headache.
I am triggering a LocationCapability authorization from within a group operation like this:
```
let op = Authorize.init(Capability.Location(.WhenInUse), completion: weakSelf.cb)
weakSelf.addOperations(op)
```
This is basically taken from your Examples repo project. The issue I run into is that this correctly _asks_ for permissions, but the Capability delegate never gets the callback. I've tracked it down to being an issue with the thread the manager is created on, and the fact that it doesn't have a runloop. I came to this conclusion after reading [this helpful answer](http://stackoverflow.com/a/19041925/1273175) and then verifying [in the documentation](https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/ …

CLLocationManager runloop issues

---

Sources/Core/iOS/AlertOperation.swift

This also fixes a bug where it wasn't possible to set a barButtonItem on an ActionSheet while presenting as a popover.

Exposing the alert property as public for customization.

---

Sources/Core/Shared/OperationQueue.swift
Tests/Core/StressTests.swift

`EXC_BAD_ACCESS` in `swift_unknownWeakLoadStrong`
`EXC_BAD_ACCESS` in `OSAtomicDequeue`
`EXC_BAD_ACCESS` in `swift_unknownWeakDestroy` [in OperationQueue.deinit]
Race condition involving the weak `delegate` property of `OperationQueue`, caused by a bug in Swift:
[**(SR-192):** Weak properties are not thread safe when reading](https://bugs.swift.org/browse/SR-192)
Should be fixed in Swift 3.0+ (see https://github.com/apple/swift/pull/1454), but is not fixed in Swift 2.2.1/2.3 (and unlikely to be).
```swift
class TestDelegate: OperationQueueDelegate {
func operationQueue(queue: OperationQueue, willAddOperation operation: NSOperation) { /* do nothing */ }
func operationQueue(queue: OperationQueue, willFinishOperation operation: NSOperation, withErrors errors: [ErrorType]) { /* do nothing */ …
```

Fix for OperationQueue.delegate crash (SR-192)

---

Operations.xcodeproj/project.pbxproj
Sources/Core/Shared/GroupOperation.swift
Sources/Core/Shared/Logging.swift
Sources/Core/Shared/Operation.swift
Sources/Core/Shared/OperationQueue.swift
Sources/Core/Shared/Queue.swift
Sources/Core/Shared/RepeatedOperation.swift
Sources/Extras/AddressBook/iOS/AddressBookOperations.swift
Tests/Core/BasicTests.swift
Tests/Core/GroupOperationTests.swift
Tests/Core/KVONotificationTests.swift
Tests/Core/OperationTests.swift
Tests/Core/StressTests.swift

This PR aggregates a series of changes made to improve Operation framework thread-safety and behavior.
Problems were identified when trying to cancel GroupOperations. Further testing and examination led to some substantial thread-safety improvements that allow a series of new Stress Tests (also included) to complete without error. (Previously, they would crash, trip asserts, etc.)
Besides thread-safety issues, several other issues were identified and fixed:
- **FIX:** GroupOperation.operations contains the initial operations twice after beginning to execute.
- **FIX:** Extraneous KVO Notifications were being sent for NSOperation keyPaths. KVO notifications are now explicit.
- **FIX:** GroupOperation now only finishes once its child operations have finished.
- **FIX:** GroupOperation now …

"Operation: Thread Safety"

---

Sources/Core/Shared/Operation.swift

Per discussion in:
https://github.com/danthorpe/Operations/pull/293
https://github.com/danthorpe/Operations/pull/358#discussion_r70167086
(For a post-3.0 release.)

Make Operation.cancel() final

---

Sources/Core/Shared/GroupOperation.swift
Sources/Core/Shared/Queue.swift
Sources/Core/Shared/ResultInjection.swift
Sources/Features/Shared/TaskOperation.swift
Tests/Core/ResultInjectionTests.swift

Adopting _Operations_ might be considered a risky proposition - it's a "framework" with all the associated issues that come with adding 3rd party dependencies.
One way which might make this less burdensome would be if there was an `Operation` type which composed simple functionality type for Result Injection.

Support composing simple types for Result injection

---

Sources/Core/Shared/ResultInjection.swift
Tests/Core/ResultInjectionTests.swift

Slight oversight from #362 which only supports synchronous _work_.

Executor must allow for asynchronous work

---

Sources/Core/Shared/GroupOperation.swift
Sources/Core/Shared/ResultInjection.swift
Tests/Core/GroupOperationTests.swift

- Make `GroupOperation.queue` internal, instead of public. (Internal so it can be tested.)
- Expose appropriate run-time editable properties of the GroupOperation’s queue as properties on GroupOperation.
> - public var maxConcurrentOperationCount: Int
> - public var suspended: Bool
> - public var qualityOfService: NSQualityOfService
- Add tests.
Per discussion in: https://github.com/danthorpe/Operations/pull/293
-----
Per discussion in:
https://github.com/danthorpe/Operations/pull/293
`GroupOperation.queue` probably shouldn’t be public, but there are run-time editable properties of the queue that ought to be configurable by framework consumers. Thus, this PR exposes those properties directly on GroupOperation.
The following properties of NSOperationQueue seem sensible to expose:
```swift …
```

Make GroupOperation's internal queue non-public, and expose appropriate properties on GroupOperation

---

Sources/Core/Shared/GatedOperation.swift
Sources/Core/Shared/GroupOperation.swift
Tests/Core/GatedOperationTests.swift

Currently the composed operation in a `GatedOperation` is not cancelled if the gate is closed. This means that any operations which depend on it or are waiting for it to ultimately finish will get stuck.
So, it's logic should change slightly so that if the gate is closed, it gets cancelled, but `GatedOperation` should always run to completion.

GatedOperation does not cancel composed operation when closed

---

Sources/Core/Shared/Operation.swift
Tests/Core/ConditionTests.swift

Essentially, if you have operation, with a dependency, and you create a condition, which has the same dependency, that dependency will get added to the queue twice (because it is added when the operation with the condition is added).
Therefore, when processing conditions, and their dependencies (i.e. the target operations _indirect dependencies_ the target operation's _direct dependencies_ must be removed from consideration.

Dependency gets added twice if it is a direct and indirect dependency

---

Sources/Core/Shared/MutuallyExclusive.swift
Sources/Core/iOS/AlertOperation.swift
Sources/Features/iOS/UserNotificationCondition.swift
Tests/Core/MutualExclusiveTests.swift

[AlertOperation](https://github.com/danthorpe/Operations/blob/9f72b42e7834e1a7d563e9430bd89a6d36c43cd1/Sources/Core/iOS/AlertOperation.swift#L54-L55) has two mutual exclusions. It really only needs the second one I believe:
```
addCondition(AlertPresentation())
addCondition(MutuallyExclusive<UIViewController>())
```
That'll make sure that other alert operations aren't run at the same time, in addition to any other `UIViewController` related operations.

AlertOperation has unnecessary mutual exclusion

---

Sources/Core/Shared/Condition.swift
Sources/Core/Shared/NegatedCondition.swift
Sources/Core/Shared/OperationCondition.swift
Tests/Core/ConditionTests.swift

A common scenario is to use a `Condition` to encapsulate business logic, to separate functionality from logic. However, at the moment this means that the operation will finish (get cancelled) with an error. This in turn is typically interpreted as an error.
So, to support "ignoring" operations using `Condition`s we can add an extra case to `ConditionResult` for `.Ignored`.

Add support for Condition to fail yet not result in an error

---

Sources/Core/Shared/OperationQueue.swift
Tests/Core/ConditionTests.swift

Consider the following dependency diagram:
```
┌─────────────────┐     ┌─────────────────┐
┌────│   Operation 1   │◀────│   Operation 2   │
│    └─────────────────┘     └─────────────────┘
│             ◇                       ◇         
│             │                       │         
│             ▼                       │         
│    ┌─────────────────┐              │         
┌────│   Condition 1   │              │         
│    └─────────────────┘              ▼         
┌───────────────┐   │                            ┌─────────────────┐
│  Dependency   │◀───────────────────────────────│   Condition 2   │
└───────────────┘                                └─────────────────┘
```
Here we have two operations, each with a condition. Both conditions share a common dependency. One …

Prevent adding indirect dependencies which are already added

---

Sources/Features/Shared/CloudKit/CloudKitOperation.swift
Tests/Features/CloudKitOperationTests.swift

~~This PR adds two new public methods:~~
~~Sets a handler block which receives a closure that can be used to add configuration blocks to the retry operation.~~
~~This will be useful for some of the new (iOS 10 / macOS 10.12) CloudKit operations that use pipelining, like [CKFetchRecordZoneChangesOperation](https://developer.apple.com/reference/cloudkit/ckfetchrecordzonechangesoperation) (where the client code may want to update the previousServerChangeToken for a zone in the event of prior partial success that was persisted).~~
~~Hypothetical pseudo-code example (doesn't work yet because support for the new CloudKit operations isn't yet included):~~
```swift
// note: this example is outdated - do not use
// 
// operation.setPrepareForRetryHandler { addConfigureBlock in
// …
```

CloudKitOperation: ability to add configuration to the next (retry) operation

---

Sources/Features/Shared/CloudKit/CloudKitInterface.swift
Sources/Features/Shared/CloudKit/CloudKitOperationExtensions.swift
Tests/Features/CloudKitOperationTests.swift

This PR:
- Adds support for the new CloudKit operations in iOS 10 / macOS 10.12
- Adds tests for those new operations
- Adds support for the remaining/new parameters in CKOperation
- Adds appropriate availability markers for the now-deprecated older CloudKit operations
- Adds watchOS support for CloudKitOperation (via some fixes in `CloudKitInterface.swift`)

Swift 2.3 - support for new CloudKit operations in iOS 10 / macOS 10.12

---

Sources/Core/Shared/Operation.swift

There isn't really any reason why the `conditions` property is internal. It can be useful to querying the attached conditions.

Make the conditions property publicly readable

---

Sources/Core/Shared/Condition.swift
Tests/Core/StressTests.swift

Previously, if a ConditionOperation’s weak `operation` var was nil when it executed, the following assertionFailure occurred:
`assertionFailure("ConditionOperation executed before operation set.”)`
(Issue: #415)
However, this was not always correct, if the weak `operation` var was set, but the operation cancelled/finished/went away before the ConditionOperation was executed.
Since this can happen, the `assertionFailure` has been replaced with a more appropriate log statement.
A StressTest was also added to cover this case and #417.

ConditionOperation "executed before operation set" assertion fix

---

Sources/Core/iOS/NetworkObserver.swift
Tests/Core/NetworkObserverTests.swift

The value of `isCancelled` was being captured by the `dispatch_after` block at `init`, and thus the check always passed and the handler was always invoked (even if `Timer.cancel()` was called).
See: https://github.com/ProcedureKit/ProcedureKit/issues/344

Fix for NetworkObserver Timer.cancel() (#344)

---

Sources/Core/iOS/NetworkObserver.swift
Tests/Core/NetworkObserverTests.swift

Previously, NetworkIndicatorController would not ensure that any existing Timer was invalidated when another observed (network) operation started prior to the Timer firing.
This resulted in potential flickering of the network activity indicator (or inaccurate state, where it disappeared too quickly) every time:
1. The number of currently-executing operations with NetworkObservers decreased to 0
2. One or more new operations with a NetworkObserver started prior to the network activity indicator disappearing (which is on a delay).

Flickering / robustness fixes for NetworkObserver / NetworkIndicatorController

---

Tests/Core/BasicTests.swift
Tests/Core/BlockConditionTests.swift
Tests/Core/GroupOperationTests.swift
Tests/Core/NegatedConditionTests.swift
Tests/Core/OperationTests.swift
Tests/Core/StressTests.swift
Tests/Features/CloudCapabilityTests.swift
Tests/Features/RemoteNotificationConditionTests.swift

If `XCTestExpectation`s are not fulfilled on the main thread, `waitForExpectationsWithTimeout` may occasionally fail with the timeout.
Fix: Ensure that `XCTestExpectation.fulfill()` is always called on the main thread.
Some places this needs to be fixed:
In BasicTests.swift:
In BlockConditionTests.swift:
In CloudCapabilitiesTests.swift:
In GroupOperationTests.swift:
In NegatedConditionTests.swift:
In RemoteNotificationConditionTests.swift:
In StressTests.swift:

Tests may randomly fail due to a bug in expectation fulfillment

---

Operations.xcodeproj/project.pbxproj

There was an extra reference in the pfxproj which Xcode UI was ignoring, but command line tools were showing a warning.
This fixes #432

Fixes warning r.e. OpenInSafariOperationTests

---

Sources/Core/Shared/Condition.swift
Sources/Core/Shared/OperationQueue.swift

Replace some instances of String interpolation, to reduce leaking in Release build on Swift 2.2.
See: #433 
As well as [this comment from an XCGLogger issue](https://github.com/DaveWoodCom/XCGLogger/issues/137#issuecomment-241268975):
> So I spent a tonne of time digging into the memory leaks. The leaks are actually in the Swift core library and our code just happened to trigger them. As you probably noticed, judging by the PR, the leak is triggered in some cases using string interpolation, so changing affected code from: "[\(owner.identifier)] " to "[" + owner.identifier + "] " avoids the leak.
> Worth noting the leaks appear to be fixed in Swift 3.

Reduce Release build leaking (due to Swift 2.x bug) (#433)

---

ProcedureKit.xcodeproj/project.pbxproj
Sources/Condition.swift
Sources/Errors.swift
Sources/Group.swift
Sources/ProcedureProcotol.swift
Sources/Testing/TestProcedure.swift
Tests/ConditionTests.swift
Tests/ResultInjectionTests.swift

For _ProcedureKit_, I'd like to revise how  `GroupOperation` (in _Operations_) managed errors from children. Previously, in v3, the group collects all of the child errors, and adds them to its own `errors` array property. This means that if a group contains another group, then the other group contains all the errors of the inner group.
Instead, for `Group`, I'd like to change it so that errors from child operations get stored inside an error aggregator, which itself is added to group's `error` property. So, if a group has 5 children of which 3 error, `GroupOperation` would report 3 errors, whereas I intend `Group` to report 1 error which in turn has 3 child errors.
This means, that `Group` can easily have child `Group` instances and the `errors` property can be easily and correctly …

Error types

---

Operations.xcodeproj/project.pbxproj
Operations_ExtensionCompatible.xcodeproj/project.pbxproj

Was incorrectly set to 10.11. Credit to @JamieWhite, issue #453.

FIX: macOS deployment target should be 10.10 (Swift 2.2) (#453)

---

Sources/Extras/CloudKit/Shared/CloudKitInterface.swift

Attempting to construct a CloudKitOperation would fail on iOS9. (See issue #461)
Example:
```swift
let _ = CloudKitOperation { CKFetchRecordChangesOperation() }
```
Would crash with `EXC_BAD_ACCESS` with the following stack trace:
```
* thread #1: [...] libswiftCore.dylib`swift_getObjCClassMetadata + 24, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x20)
frame #0: [...] libswiftCore.dylib`swift_getObjCClassMetadata + 24
frame #1: [...] TestOperations`type metadata accessor for CKShareMetadata + 45 at AppDelegate.swift:0
frame #2: [...] TestOperations`type metadata accessor for CloudKitOperation<CKFetchRecordChangesOperation> + 246 at AppDelegate.swift:0
```
This PR fixes the issue by restructuring the CKOperationType protocol into two protocols:
- …

FIX: CloudKitOperation EXC_BAD_ACCESS on iOS9 (Swift 2.3) (#461)

---

ProcedureKit.xcodeproj/project.pbxproj
Sources/MutualExclusion.swift
Sources/Procedure.swift
Sources/ProcedureQueue.swift
Sources/Testing/ProcedureKitTestCase.swift
Tests/ConditionTests.swift
Tests/MutualExclusivityTests.swift
Tests/Stress Tests/ProcedureStressTests.swift

In addition to `MutuallyExclusive<T>` this ticket also refines the condition API to use
```swift
procedure.attach(condition: condition)
```

Add support for mutual exclusive conditions

---

Sources/Procedure.swift
Sources/Testing/ProcedureKitTestCase.swift
Tests/Stress Tests/ProcedureStressTests.swift

Fixes: Procedure would not finish if `_finish()` was called from `main()`. (ex. If cancelled before executing.)
Also adds a StressTest to cover concurrent calls to `finish()`.

Procedure finishing fixes

---

ProcedureKit.xcodeproj/project.pbxproj
Sources/Condition.swift
Sources/Group.swift
Sources/Identity.swift
Sources/Procedure.swift
Sources/Testing/TestProcedure.swift
Tests/GroupTests.swift
Tests/NegatedConditionTests.swift
Tests/ProcedureTests.swift
Tests/SilentConditionTests.swift

`Procedure` should automatically set its name to the dynamic type. Additionally we need to restore the nested `Identity` struct.

Procedure name and identity

---

ProcedureKit.xcodeproj/project.pbxproj
Sources/Block.swift
Sources/Transform.swift
Tests/TransformProcedureTests.swift

`TransformProcedure` should automatically cancel if the requirement is not set.

Refactor TransformProcedure & BlockProcedure

---

Sources/Repeat.swift

There is a regression of the release bug associated with `MapIterator`.

Regression with Release build configuration

---

Sources/Composed.swift
Sources/Location/ReverseGeocode.swift
Sources/Location/UserLocation.swift
Sources/Procedure.swift
Sources/Testing/CapabilityTestCase.swift
Sources/Testing/RepeatTestCase.swift
Tests/BlockConditionTests.swift
Tests/ConditionTests.swift
Tests/MutualExclusivityTests.swift
Tests/NegatedConditionTests.swift
Tests/NoFailedDependenciesConditionTests.swift
Tests/Stress Tests/ProcedureStressTests.swift

I think, in retrospect, that it's more discoverable if the API is `add`

Rename attach(condition: Condition) back to add

---

Sources/ResultInjection.swift

Seems as though there is a problem with the way that the `injectDependency` API is defined, as it cannot be correctly used for some reason.

Fix issues with injecting dependencies

---

Sources/Location/ReverseGeocodeUserLocation.swift
Sources/ResultInjection.swift
Tests/ResultInjectionTests.swift

Because a lot of the result injection procedures currently necessitate the use of explicitly unwrapped optionals - it's increasingly tricky to use result injection.

Add transform block result injection API

---

Sources/Any.swift

It should effectively be entirely transparent, which means that the composed procedure's log is not impacted, but should not see `AnyProcedure<(), String>` adding itself to queues or anything

AnyProcedure should suppress its log functionality

---

Sources/Group.swift
Sources/ProcedureQueue.swift
Tests/GroupTests.swift
Tests/Location/ReverseGeocodeUserLocationProcedureTests.swift

There is a bug in the way that `GroupProcedure` manages the errors from its children. The scenario is this:
1. The group is cancelled - possibly because of a failed condition.
2. The group's internal will cancel observer kicks in, and cancels all of its children with an error (`.parentDidCancel`).
3. The children all finish with an error
4. The group, acting as the queue's delegate, receives the finishing, and records all the errors of the children.
This makes diagnosing errors actually quite tricky as while its important that the children receive the correct error, from outside the `GroupProcedure` it is more important that these are suppressed.
So, I think all that is needed is some checks on `isCancelled` in the appropriate queue delegate methods.

Bug with how GroupProcedure manages the errors of its children.

---

Sources/Collection+ProcedureKit.swift
Sources/Network/NetworkData.swift

Possibly there is a bug here, as `URLSession` is a class cluster, so force casting the result of `URLSession.shared` will possibly not work.

Investigate issue with NetworkDataProcedure

---

Sources/Cloud/CloudKitCapability.swift
Sources/Cloud/CloudKitSupport.swift
Sources/Location/LocationCapability.swift
Sources/Location/LocationSupport.swift
Sources/Location/ReverseGeocode.swift
Sources/Location/ReverseGeocodeUserLocation.swift
Sources/Location/UserLocation.swift
Sources/Logging.swift
Sources/Mobile/BackgroundObserver.swift
Sources/Mobile/NetworkObserver.swift
Sources/Network/NetworkData.swift
Sources/Network/NetworkSupport.swift
Sources/Testing/QueueTestDelegate.swift
Supporting Files/ProcedureKitCloud.h
Supporting Files/ProcedureKitLocation.h
Supporting Files/ProcedureKitMac.h
Supporting Files/ProcedureKitMobile.h
Supporting Files/ProcedureKitNetwork.h
Supporting Files/ProcedureKitTV.h
Supporting Files/TestingProcedureKit.h

This is to support subspaces with CocoaPods where all classes will get put into a single ProcedureKit module.

Move ProcedureKit imports to umbrella headers

---

ProcedureKit.podspec
ProcedureKit.xcodeproj/project.pbxproj
Sources/Cloud/CloudKitCapability.swift
Sources/Cloud/CloudKitSupport.swift
Sources/Location/LocationCapability.swift
Sources/Location/LocationSupport.swift
Sources/Location/ReverseGeocode.swift
Sources/Location/ReverseGeocodeUserLocation.swift
Sources/Location/UserLocation.swift
Sources/Testing/CapabilityTestCase.swift
Sources/Testing/GroupTestCase.swift
Sources/Testing/ProcedureKitTestCase.swift
Sources/Testing/QueueTestDelegate.swift
Sources/Testing/RepeatTestCase.swift
Sources/Testing/StressTestCase.swift
Sources/Testing/TestCondition.swift
Sources/Testing/TestProcedure.swift
Sources/Testing/TestableNetwork.swift
Sources/Testing/XCTAsserts.swift
Supporting Files/ProcedureKitCloud.h
Supporting Files/ProcedureKitLocation.h
Supporting Files/TestingProcedureKit.h
Tests/Cloud/TestableCloudKitContainer.swift
Tests/Location/LocationCapabilityTests.swift
Tests/Location/ReverseGeocodeProcedureTests.swift
Tests/Location/UserLocationProcedureTests.swift
Tests/LoggerTests.swift

Need to create ~subspecs~ podspecs for the "sub modules". The way CocoaPods subspaces work, means that there is a single module for each pod, and the subspec just defines what goes in the module. This actually is a great, but it's not a compatible setup with Carthage/SPM/Manual. Because it means that code in say `ProcedureKitNetwork` will have `import ProcedureKit` inside it, which throws up a warning.
So, I think what we need is to have multiple podspecs for each framework.
- `ProcedureKit` the default
- `TestingProcedureKit`
- `ProcedureKitMobile`
- `ProcedureKitLocation`

Generate ProcedureKit podspecs

---

ProcedureKit.xcodeproj/project.pbxproj
Sources/Any.swift
Sources/Capability.swift
Sources/Collection+ProcedureKit.swift
Sources/Filter.swift
Sources/Group.swift
Sources/Location/ReverseGeocode.swift
Sources/Location/ReverseGeocodeUserLocation.swift
Sources/Location/UserLocation.swift
Sources/Map.swift
Sources/Network/NetworkData.swift
Sources/Network/NetworkResilience.swift
Sources/Operation+ProcedureKit.swift
Sources/Procedure.swift
Sources/Reduce.swift
Sources/ResultInjection.swift
Sources/Testing/TestProcedure.swift
Sources/Transform.swift
Tests/AnyProcedureTests.swift
Tests/CapabilityTests.swift
Tests/FilterProcedureTests.swift
Tests/Location/ReverseGeocodeProcedureTests.swift
Tests/Location/UserLocationProcedureTests.swift
Tests/MapProcedureTests.swift
Tests/ProcedureTests.swift
Tests/ReduceProcedureTests.swift
Tests/ResultInjectionTests.swift
Tests/TransformProcedureTests.swift

There is a particular issue with result injection, which is a result of Swift's initialisation strategy, which means that `requirement` and `result` often need to be explicitly unwrapped optionals.
A better way to manage this is to define a different either type, a `PendingValue` e.g.
```swift
enum PendingValue<T> {
case pending
case value(T)
}
```
This will allow both `requirement` and `result` properties to now be `PendingValue<T>` properties, and ultimately remove the complications of `!` all over the place.

Refactor ResultInjection - again

---

Tests/Stress Tests/BlockProcedureStressTests.swift

**Fix `test__cancel_block_procedure()` failures:**
It was possible for the testing BlockProcedure to finish prior to the `block.cancel()` call, which would result in some of the BlockProcedures never cancelling (as they had finished first), and a failing test.
Fixed by using a semaphore inside the BlockProcedure’s block.
Additionally, the test now waits for all BlockProcedures to cancel *and* finish.
**Add a new stress test for BlockProcedure cancelling & finishing behavior:**
This test, `test_cancel_or_finish_block_procedure()`, allows for possible races between cancelling and finishing (which the previous cancellation test now does not).

BlockProcedure StressTest fixes/enhancements

---

Sources/MutualExclusion.swift

The ExclusivityManager was using `DispatchQueue.initiated`, which returns a global queue that is a **concurrent** queue, however its internals are dependent upon **serial** execution of add/remove.
Fixed to create and use a serial queue.
(Reported by @myexec in #543.)

Fix ExclusivityManager synchronization bug (#543)

---

Sources/Network/NetworkData.swift
Sources/Network/NetworkResilience.swift
Sources/Network/NetworkSupport.swift
Tests/Network/NetworkDataProcedureTests.swift

With Swift 3.0 it's kinda annoying that tuples can no longer have labels. Grr, which means that we can't have `(data: Data, response: HTTPURLResponse)`.

Create a struct for NetworkDataProcedure

---

Sources/Testing/QueueTestDelegate.swift

QueueTestDelegate was not thread-safe. This could result in crashes running random tests.
Fixed by making QueueTestDelegate’s methods thread-safe.

Fix test crashes caused by QueueTestDelegate thread-safety

---

ProcedureKit.xcodeproj/project.pbxproj
Sources/Testing/ConcurrencyTestCase.swift
Tests/MutualExclusivityTests.swift

Add new ConcurrencyTestCase (and helper functionality) for concurrency testing.
Add Mutual Exclusivity concurrency testing that covers the normal cases, and also covers #543.
(The existing `test__mutually_exclusive_operation_are_run_exclusively` is not guaranteed to catch all cases because there is no guarantee that the two operations, even if scheduled to run concurrently, will actually modify the `text` var at the same time. Additionally, on failure, the test may crash instead of displaying failure information.)

Add Mutual Exclusivity concurrency testing

---

.fastlane/Fastfile

The `Location (iOS)` CI job, actually runs the `Mobile (iOS)` scheme. Whoops.

Fix mistake in Fastfile

---

ProcedureKit.xcodeproj/project.pbxproj
Sources/Network/NetworkSupport.swift
Sources/Network/NetworkUpload.swift
Sources/Testing/TestableNetwork.swift
Tests/Network/NetworkUploadProcedureTests.swift
Tests/Network/ProcedureKitNetworkTests.swift

The implementation class and test has been largely inspired by
`NetworkDataProcedure`.
The requirement type is currently a pending value of a tuple.
Maybe would it make more sense to create a dedicated struct to add more
clarity in the case of dependencies injection ?

Add NetworkUploadProcedure.

---

Sources/Condition.swift
Sources/NegatedCondition.swift
Sources/Procedure.swift
Tests/CapabilityTests.swift
Tests/ConditionTests.swift

At the moment, `Condition` has a result property, which is not a `PendingValue<T>`. Subclasses cannot therefore conform to `ResultInjection`.

Fix Condition to support ResultInjection

---

Tests/Location/TestableLocationServices.swift

To replicate [CLGeocoder.reverseGeocodeLocation(_:completionHandler:)](https://developer.apple.com/reference/corelocation/clgeocoder/1423621-reversegeocodelocation), the completion block must be called on the main thread.

TestableReverseGeocoder should call completionHandler block on the main thread

---

Sources/Procedure.swift

Append directly to the protected observers array.
This avoids a get (read) -> copy -> append to copy -> set (write) chain that introduces a performance penalty and a race condition.

Procedure.add(observer:) performance/thread-safety tweak

---

Sources/ProcedureQueue.swift

This is useful to enable overriding in test code.
Notes: 
* `NSOperationQueue.addOperation`  is already `open`
* All other methods in this file are `open`

Make ProcedureQueue.add(operation: Operation) method open for subclassing

---

Sources/Mobile/NetworkObserver.swift
Tests/Mobile/NetworkObserverTests.swift

NetworkObserver in ProcedureKit 4.0 beta 4 is not currently thread-safe, because NetworkActivityController's start() and stop() methods are not currently thread-safe.
This can result in crashes and incorrect behavior if multiple Procedures with NetworkObservers perform the right state transitions (and observer callbacks) concurrently.
Also fixes some of the associated tests.

NetworkObserver thread-safety (#576)

---

Tests/GroupTests.swift

Tests to ensure that the base GroupProcedure ProcedureQueue delegate implementation ignores delegate callbacks from other queues.

Additional GroupProcedure tests

---

Sources/Network/NetworkSupport.swift
Sources/Network/NetworkUpload.swift

Fix for #585.
Declaring a constructor for the `HTTPRequirement` allows the
construction of the struct without any issue.

Proposal to fix #585.

---

.swiftlint.yml
ProcedureKit.xcodeproj/project.pbxproj
Sources/Group.swift
Sources/Logging.swift
Sources/Network/NetworkData.swift
Sources/Network/NetworkDownload.swift
Sources/Network/NetworkReachability.swift
Sources/Network/NetworkReachable.swift
Sources/Network/NetworkSupport.swift
Sources/Network/NetworkUpload.swift
Sources/Procedure.swift
Sources/Reachability.swift
Sources/Support.swift
Sources/Testing/ProcedureKitTestCase.swift
Sources/Testing/TestableNetworkReachability.swift
Tests/Network/NetworkDataProcedureTests.swift
Tests/Network/NetworkDownloadProcedureTests.swift
Tests/Network/NetworkReachabilityTests.swift
Tests/Network/NetworkReachableProcedureTests.swift
Tests/Network/NetworkUploadProcedureTests.swift
Tests/ReachabilityTests.swift

```swift
final public class ReachableProcedure<T: ProcedureProtocol>: RetryProcedure<T> 
where T: AssociatedErrorProtocol, T.AssociatedError: ReachableNetworkProcedureError {
// etc
}
```

ReachableProcedure

---

.ci/buildkite/pipeline.template.yml
.fastlane/Fastfile
ProcedureKit.xcodeproj/xcshareddata/xcschemes/Stress Tests.xcscheme

Improve how stress tests are run in CI

---

Sources/Testing/StressTestCase.swift
Tests/Stress Tests/GroupStressTests.swift
Tests/Stress Tests/ProcedureStressTests.swift

Per #555, since OSAtomicIncrement32 and friends are deprecated, moved this to a simple lock-based implementation that fixes the issues.

Fix StressTestCase Batch counters thread-safety (#555)

---

Sources/Repeat.swift

Fix issues identified by an audit and Thread Sanitizer.
(There were data race scenarios surrounding the access/modification of the internal properties.)
> Notes:
> 
> The `_repeatStateLock` is a `NSRecursiveLock` because `addNextOperation`'s `shouldAddNext` block may access protected properties of the RepeatProcedure (amongst other reasons).

RepeatProcedure thread-safety fixes

---

Sources/Logging.swift
Sources/Procedure.swift
Sources/Support.swift

Fixes issues identified by an audit and Thread Sanitizer.
`add(directDependency:)`
`remove(directDependency:)`
`add(condition:)`
are now thread-safe.
In addition, accessing the various properties are now thread-safe.
And a data race that was not prevented by the existing use of locks surrounding `_error` is resolved.

Procedure & Support thread-safety fixes

---

Sources/Network/NetworkData.swift
Sources/Network/NetworkDownload.swift
Sources/Network/NetworkUpload.swift

Thread-safety for `input` and `output`, as well as in the event of cancellation (which can occur on any thread).

NetworkDataProcedure, NetworkDownloadProcedure, NetworkUploadProcedure thread-safety

---

Sources/Mobile/BackgroundObserver.swift

To support iOS < 9.0 and macOS < 10.11, NotificationCenter observers **must** be properly removed, or a crash may result.

Fix BackgroundObserver on iOS 8.x

---

Sources/Network/NetworkData.swift
Sources/Network/NetworkDownload.swift
Sources/Network/NetworkUpload.swift

> Must check `!isCancelled` inside the `stateLock`, or it is possible for a `NetworkDataProcedure` / `NetworkDownloadProcedure` / `NetworkUploadProcedure` that is cancelled after the `execute()` function is called, but before the acquisition of the `stateLock` inside it, to continue to create a network task.
> Per Slack discussion.

Network*Procedure tweaks

---

Sources/Group.swift
Sources/Procedure.swift
Sources/Retry.swift
Sources/TimeoutObserver.swift
Tests/RetryProcedureTests.swift

See issue #622.
Underlying problems fixed:
> RetryIterator’s RetryFailureInfo (`info`) property is set right before `addNextOperation()` is called, which calls `next()` on the RetryIterator (which then uses the RetryFailureInfo).
> 
> Ultimately, the RetryFailureInfo contains strong references to the RetryProcedure (`addOperations`, `configure`...). And since the RetryProcedure owns the RetryIterator, which owns the RetryFailureInfo… We end up with a reference cycle.
> 
> As an immediate quick fix, since the RetryFailureInfo is only used in the call to `addNextOperation()`, set it back to `.none` after the call.
> Previously, a GroupProcedure that was created and released but never added to a queue would leak the child operations on its internal OperationQueue.
> 
> To ensure that it is …

Memory leaks highlighted by Visual Memory Debugger (#622)

---

.ci/buildkite/pipeline.template.yml

Add steps to CI for TryProcedureKit integration

---

ProcedureKit.xcodeproj/project.pbxproj
Sources/Mobile/Alert.swift
Sources/Mobile/Presentation.swift
Sources/Mobile/UI.swift
Sources/ProcedureResult.swift
Tests/Mobile/AlertProcedureTests.swift
Tests/Mobile/PresentationProcedureTests.swift
Tests/Mobile/UIProcedureTests.swift

Supports `UIProcedure` and `AlertProcedure` in _ProcedureKitMobile_.
Usage is a bit like this:
```swift
let alert = AlertProcedure(presentAlertFrom: self)
alert.add(actionWithTitle: "Sweet") { alert, action in
alert.log.info(message: "Running the handler!")
}
alert.title = "Hello World"
alert.message = "This is a message in an alert"
queue.add(operation: alert)
```

UIProcedure & AlertProcedure

---

ProcedureKit.xcodeproj/project.pbxproj
ProcessProcedureTests.swift
Sources/Mac/Process.swift
Sources/Support.swift

`NSTask`/`Process` is listed as a Thread-Unsafe Class in the [Foundation Framework Thread Safety guide](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Multithreading/ThreadSafetySummary/ThreadSafetySummary.html#//apple_ref/doc/uid/10000057i-CH12-125664).
Additionally, when an NSTask/Process is `launch()`ed on a thread that goes away before it does, [a crash can result](https://web.archive.org/web/20111213185028/http://cocoadev.com/index.pl?NSTaskTermination).
As such, some major modifications to ProcessProcedure are necessary.
- `init(…)` now takes all the possible configuration parameters for the Process, instead of a Process instance (the only required parameter is `launchPath`)
- the ProcessProcedure is now responsible for creating the Process object and …

ProcessProcedure improvements & thread-safety

---

Sources/Testing/TestableNetwork.swift
Tests/Network/NetworkDataProcedureTests.swift
Tests/Network/NetworkDownloadProcedureTests.swift
Tests/Network/NetworkUploadProcedureTests.swift

- Enhance `TestableURLSessionTask` and `TestableURLSessionTaskFactory` cancellation support
The behavior now better replicates NSURLSession/NSURLSessionTask behavior on cancellation, including providing the proper error to the completionHandler (and calling the completionHandler early if cancelled).
- More cancellation tests for `NetworkDataProcedure`
- More cancellation tests for `NetworkDownloadProcedure`
- More cancellation tests for `NetworkUploadProcedure`

NetworkProcedure cancellation testing enhancements

---

Sources/Cloud/CKAcceptSharesOperation.swift
Sources/Cloud/CKFetchRecordChangesOperation.swift
Sources/Cloud/CKFetchRecordZoneChangesOperation.swift
Sources/Cloud/CKFetchShareMetadataOperation.swift
Sources/Cloud/CKFetchShareParticipantsOperation.swift
Sources/Cloud/CKMarkNotificationsReadOperation.swift
Sources/Cloud/CKModifyRecordsOperation.swift
Sources/Cloud/CKOperation.swift

Xcode 8.2 beta 2 (8C30a) changed several of the CKOperation (and subclasses') property/block types slightly. Make these `associatedtype`s so they work on both Xcode 8.2 beta 2 and earlier versions of Xcode 8.

Resolve ProcedureKitCloud compilation issues with Xcode 8.2 beta 2

---

Sources/Testing/TestableNetwork.swift
Sources/Testing/TestableNetworkReachability.swift

Certain ProcedureKitNetwork tests occasionally fail:
```
[18:25:34]: ▸ Failing tests:
[18:25:34]: ▸ -[NetworkProcedureTests test__waits_for_reachability_change_before_retrying()]
[18:25:34]: ▸ -[NetworkReachabilityWaitProcedureTests test__procedure_waits_until_network_is_reachable()]
[18:25:34]: ▸ -[ReachabilityManagerTests test__when_connected_block_is_run()]
[18:25:34]: ▸ ** TEST FAILED **
```
Some of this may be due to a lack of thread-safety in `TestableURLSessionTaskFactory` and `TestableNetworkReachability`.

NetworkProcedure testing improvements

---

Sources/Condition.swift
Sources/Group.swift
Sources/MutualExclusion.swift
Sources/Procedure.swift
Sources/ProcedureQueue.swift
Sources/Repeat.swift

Mark non-open properties/methods as `final` unless they are explicitly audited/purposed for overriding to ensure that later attempts to override (even internally) do not silently succeed without reviewing side-effects/implications.

`Final` cleanup

---

Sources/Errors.swift

Swift leaks memory when converting `ProcedureKitError` to a string unless it conforms to `CustomStringConvertible` and provides its own `var description: String { get }` implementation. (Affects at least: Swift 3.0.1 & Xcode 8.1)
Symptoms: Malloc 48 byte leaks
This workaround eliminates the leaks.

ProcedureKitError string conversion memory leak fix (Swift bug) (#660)

---

Sources/TimeoutObserver.swift
Tests/TimeoutObserverTests.swift

- Utilize a new ProcedureTimeoutRegistrar to handle the lifetime of timeout timers.
- When a Procedure finishes (or a timer fires), cancel all outstanding timers for that Procedure. (Thus, a TimeoutObserver with a long timeout will immediately deallocate its timers and associated timeout blocks when the Procedure finishes, instead of keeping the timers / timeout blocks in memory until the timeout passes.)
- Eliminate impact on the main thread/queue by executing the timer blocks on a private queue.

TimeoutObserver improvements

---

ProcedureKit.xcodeproj/project.pbxproj

The current dev branch won't build a release build. Results in error "Ad Hoc code signing is not allowed with SDK 'iOS 10.2'" Building from Carthage works, but we're not using Carthage. We have PK set up as a dependent subproject, so our release builds fail.

Fixed code signing issue that prevented building release builds

---

Sources/ProcedureKit/Retry.swift
Sources/ProcedureKitNetwork/Network.swift
Tests/ProcedureKitTests/RetryProcedureTests.swift

A likely side-effect of the transition from Operations -> ProcedureKit was a `RetryProcedure` class that takes any `Operation` subclass.
But since `Operation` is now `Foundation.Operation` (i.e. `NSOperation`), this poses a problem: `Foundation.Operation` provides no error information, and thus Operation subclasses will never trigger the Retry behavior (they can't report errors through the GroupProcedure machinery - only Procedure subclasses can). i.e. `RetryProcedure` is only useful for `Procedure` subclasses.
This PR makes that explicit by changing:
```diff
- class RetryProcedure<T: Operation>
+ class RetryProcedure<T: Procedure>
```

Limit RetryProcedure to Procedure subclasses

---

Sources/ProcedureKit/Capability.swift
Tests/ProcedureKitTests/CapabilityTests.swift

Previously, an `AuthorizedFor` condition ensured that the Procedure to which it was added was mutually exclusive with any other Procedures with the same `AuthorizedFor` condition (where the base `CapabilityProtocol` was the same).
However, what is needed is for the `AuthorizeCapabilityProcedure` (produced by the `AuthorizedFor` condition, and which can trigger a prompt for the capability) to be mutually exclusive with other `AuthorizeCapabilityProcedure`s with the same base `CapabilityProtocol`.
This change ensure that two Procedures do not try to prompt for the same authorization/permission concurrently - but that _once they have acquired the authorization/permission_, the Procedures may then execute concurrently (unless some other MutuallyExclusive condition or dependency prevents it).

Improve AuthorizedFor mutual exclusivity

---

Sources/ProcedureKit/Capability.swift
Sources/ProcedureKit/Condition.swift
Sources/ProcedureKit/Group.swift
Sources/ProcedureKit/MutualExclusion.swift
Sources/ProcedureKit/Procedure.swift
Sources/ProcedureKit/ProcedureQueue.swift
Sources/ProcedureKit/SilentCondition.swift
Sources/TestingProcedureKit/TestCondition.swift
Sources/TestingProcedureKit/XCTAsserts.swift
Tests/ProcedureKitStressTests/ProcedureStressTests.swift
Tests/ProcedureKitTests/CapabilityTests.swift
Tests/ProcedureKitTests/ConditionTests.swift
Tests/ProcedureKitTests/MutualExclusivityTests.swift
Tests/ProcedureKitTests/SilentConditionTests.swift

This PR encompasses a major refactor of Conditions in ProcedureKit, improving performance, fixing bugs, and adding new features (while also expanding test coverage and documentation).
- `Conditions` are no longer `Procedure` subclasses, and are lighter-weight.
- `Condition` processing is faster, and supports short-circuit evaluation for considerable performance improvements.
- MutualExclusivity is now evaluated post-dependencies and condition evaluation (i.e. immediately before execute), resolving numerous issues and edge cases.
- Bugs have been fixed.
- Internal implementation details are no longer exposed to user code unexpectedly.
- Added a new `CompoundCondition` (and `AndCondition` / `OrCondition`) to support logical “&&” and “||” operations on `Conditions`.
- A *lot* more …

Improve Conditions

---

Sources/ProcedureKit/ProcedureResult.swift
Tests/ProcedureKitTests/ResultInjectionTests.swift

Currently, dependency injection uses the error `parentCancelledWithErrors` when the dependency has been cancelled. To aide debugging, we should probably add a new unique error for this case (suggestion: `dependencyCancelledWithErrors`).
```swift
dependency.addDidCancelBlockObserver { [weak self] dependency, errors in
if let strongSelf = self {
strongSelf.cancel(withError: ProcedureKitError.parent(cancelledWithErrors: errors))
}
}
```
See: https://github.com/ProcedureKit/ProcedureKit/blob/08a0d37ba66f084073fd687bbd99a34fa9fe1fff/Sources/ProcedureKit/ProcedureResult.swift#L156

Dependency injection cancellation error

---

Sources/ProcedureKit/DispatchQueue+ProcedureKit.swift
Sources/ProcedureKit/Procedure.swift
Sources/ProcedureKit/ProcedureEventQueue.swift
Tests/ProcedureKitTests/GroupTests.swift
Tests/ProcedureKitTests/ProcedureTests.swift

If a Procedure is enqueued on a ProcedureQueue that specifies an `underlyingQueue`, the Procedure’s `execute()` function should run on the `underlyingQueue`.

Procedure's `execute()` function should utilize the ProcedureQueue.underlyingQueue, if set

---

Sources/TestingProcedureKit/ConcurrencyTestCase.swift
Sources/TestingProcedureKit/GroupTestCase.swift
Tests/ProcedureKitTests/BlockObserverTests.swift
Tests/ProcedureKitTests/ConditionTests.swift
Tests/ProcedureKitTests/GroupTests.swift
Tests/ProcedureKitTests/MutualExclusivityTests.swift
Tests/ProcedureKitTests/NetworkObserverTests.swift
Tests/ProcedureKitTests/ProcedureTests.swift
Tests/ProcedureKitTests/TimeoutObserverTests.swift

1. Two of the dependency-related Condition tests could (rarely) fail due to a race condition in the tests themselves.
2. `test__timeout_observer_where_procedure_is_already_cancelled` could fail because the Procedure was being cancelled via a call to `check(procedure:)` (which executes its block after the Procedure has been added to a queue).
3. Robustness improvements to NetworkObserverTests.
The block inside the `TestableNetworkActivityIndicator` is ultimately dispatched asynchronously by the `NetworkActivityController` and, thus, its ordering relative to an individual test finishing (and `tearDown()` being called) may depend on the test specifics and other factors. Therefore, do not use `self._changes`; instead capture the specific  `_changes` for the test.
4. Robustness improvements to …

Robustness fixes for tests

---

Sources/TestingProcedureKit/ProcedureKitTestCase.swift
Sources/TestingProcedureKit/QueueTestDelegate.swift
Tests/ProcedureKitTests/ProcedureTests.swift

Several of the `QueueDelegateTests` could (rarely) fail due to a race condition in the tests themselves (related to not properly waiting for the `didFinish` delegate callback).

Robustness fixes for QueueDelegateTests

---

Tests/ProcedureKitTests/BlockObserverTests.swift

`test__will_add_synchronized` and `test__did_add_synchronized` could (rarely) hit a race condition in the tests themselves and fail.

Robustness fixes for BlockObserverSynchronizationTests

---

Sources/ProcedureKit/Delay.swift
Sources/ProcedureKit/ProcedureEventQueue.swift

Fix a (rare) data race in `DelayProcedure` (discovered via Thread Sanitizer) by ensuring that the `DispatchSourceTimer` is initialized to use the `DelayProcedure`’s internal EventQueue. (The race involved the release of the `DispatchSourceTimer`’s `eventHandler` block.)

Fix a (rare) data race in DelayProcedure

---

Sources/ProcedureKit/Collection+ProcedureKit.swift
Tests/ProcedureKitTests/ProcedureTests.swift

When the `.then` API is used with a Collection of Operations, **_all_** the operations in the receiver (collection) should be added as dependencies of the argument.
Originally, the `.then { }` API was created to solve a particular use case (#176), in which single operation after single operation would be joined into a chain of dependencies, all using the `.then { }` API.
The initial implementation:
- Took the last Operation in a chain (collection), and added it as a dependency to the argument.
So, if it is used as the initial example use-case suggested, it would succeed as expected:
```swift
static func sequenceOfOperations(completionHandler: () -> ()) {
sharedManager.addOperations(InterruptibleNetworkOperation<HTTPBinResponse>(request: APIRouter.GET)
.then { …
```

Improve .then { } API

---

Sources/ProcedureKitMac/Process.swift
Tests/ProcedureKitMacTests/ProcessProcedureTests.swift

**New Features**:
- `ProcessProcedure` now conforms to **`InputProcedure`**, and the `LaunchRequest` can be provided via result injection.
- `ProcessProcedure` now conforms to **`OutputProcedure`**.
- `ProcessProcedure` explicitly handles termination due to uncaught signals by default.
- `ProcessProcedure` dispatches the `processDidExitCleanly` and `processDidLaunch ` handlers on its internal, serial EventQueue.
- **`processDidLaunch`** handler: execute code after the `ProcessProcedure` starts its Process
**Breaking Changes**:
- `ProcessProcedure` now provides the `Process.terminationStatus` **and** the `Process.terminationReason` to the **`processDidExitCleanly`** handler:
```diff
- public typealias ProcessDidExitCleanly = (Int) -> Bool
+ public typealias ProcessDidExitCleanly = (Int32, …
```

Improve ProcessProcedure

---

Sources/TestingProcedureKit/ProcedureKitTestCase.swift

`makeFinishingProcedure` previously created a memory cycle by:
1. Adding the target procedure as a dependency of the `finishingProcedure` (strong reference: `finishingProcedure` -> `target`)
2. Adding a ‘WillAddOperation’ observer to the target procedure that captured the `finishingProcedure` (strong reference: `target` ->`finishingProcedure`)

Fix a memory cycle in the testing framework helpers

---

Sources/ProcedureKit/Collection+ProcedureKit.swift
Sources/ProcedureKit/Condition.swift
Sources/ProcedureKitCloud/CKAcceptSharesOperation.swift
Sources/ProcedureKitCloud/CKDiscoverAllContactsOperation.swift
Sources/ProcedureKitCloud/CKDiscoverAllUserIdentitiesOperation.swift
Sources/ProcedureKitCloud/CKDiscoverUserIdentitiesOperation.swift
Sources/ProcedureKitCloud/CKDiscoverUserInfosOperation.swift
Sources/ProcedureKitCloud/CKFetchDatabaseChangesOperation.swift
Sources/ProcedureKitCloud/CKFetchNotificationChangesOperation.swift
Sources/ProcedureKitCloud/CKFetchRecordChangesOperation.swift
Sources/ProcedureKitCloud/CKFetchRecordZoneChangesOperation.swift
Sources/ProcedureKitCloud/CKFetchRecordZonesOperation.swift
Sources/ProcedureKitCloud/CKFetchRecordsOperation.swift
Sources/ProcedureKitCloud/CKFetchShareMetadataOperation.swift
Sources/ProcedureKitCloud/CKFetchShareParticipantsOperation.swift
Sources/ProcedureKitCloud/CKFetchSubscriptionsOperation.swift
Sources/ProcedureKitCloud/CKMarkNotificationsReadOperation.swift
Sources/ProcedureKitCloud/CKModifyBadgeOperation.swift
Sources/ProcedureKitCloud/CKModifyRecordZonesOperation.swift
Sources/ProcedureKitCloud/CKModifyRecordsOperation.swift
Sources/ProcedureKitCloud/CKModifySubscriptionsOperation.swift
Sources/ProcedureKitCloud/CKOperation.swift
Sources/ProcedureKitCloud/CKQueryOperation.swift
Sources/TestingProcedureKit/ProcedureKitTestCase.swift
Sources/TestingProcedureKit/XCTAsserts.swift

The Swift 4 compiler is stricter, and warns about redundant conformance constraints.

Resolve redundant conformance constraints [Swift 4]

---

Sources/ProcedureKit/Support.swift

This particular use really ought to be `Strideable` anyway.

Fix 'Integer' protocol is unavailable [Swift 4]

---

Sources/ProcedureKit/Group.swift

`Retry.swift:134:24: Declarations from extensions cannot be overridden yet` (The Swift 4 compiler catches a case that the Swift 3 compiler was happy to allow.)
Resolved by moving the declaration of `child(_:didAttemptRecoveryFromErrors:)` in Group.swift from an extension of GroupProcedure to the main `class GroupProcedure`.

Resolve Group/RetryProcedure overridden extension declaration [Swift 4]

---

Sources/ProcedureKit/Logging.swift
Tests/ProcedureKitTests/LoggerTests.swift

`Logging.swift:168:21: Closure tuple parameter '(message: String, severity: LogSeverity, file: String, function: String, line: Int)' does not support destructuring`
This was apparently [never really intended to work](https://bugs.swift.org/browse/SR-4738), but there was special-case behavior for a single tuple argument. The Swift 4 compiler is now stricter about rejecting it.

Logger fix for `closure tuple parameter does not support destructuring` [Swift 4]

---

Sources/ProcedureKit/ProcedureEventQueue.swift

In Swift 4, `DispatchQueue.setSpecific(key:value:)` now takes an optional `value` - enabling the clearing of specific keys (by passing a nil `value`).

Fix for Swift4 DispatchQueue `setSpecific` changes

---

Sources/TestingProcedureKit/RepeatTestCase.swift
Tests/ProcedureKitCloudTests/CKFetchRecordChangesOperationTests.swift
Tests/ProcedureKitNetworkTests/NetworkDataProcedureTests.swift
Tests/ProcedureKitNetworkTests/NetworkDownloadProcedureTests.swift
Tests/ProcedureKitNetworkTests/NetworkUploadProcedureTests.swift
Tests/ProcedureKitTests/BlockObserverTests.swift
Tests/ProcedureKitTests/FinishingTests.swift
Tests/ProcedureKitTests/GroupTests.swift

The Swift 4 compiler is stricter about how closure input parameters are specified.

Fix closure input parameters [Swift 4]

---

Sources/ProcedureKit/NetworkObserver.swift
Tests/ProcedureKitTests/NetworkObserverTests.swift

In Swift 4, `UIApplication.networkActivityIndicatorVisible` becomes `UIApplication.isNetworkActivityIndicatorVisible`.
Match this in the NetworkActivityIndicatorProtocol on Swift 4.

Fix: In Swift 4, `networkActivityIndicatorVisible` -> `isNetworkActivityIndicatorVisible`

---

Sources/ProcedureKitCloud/CKOperation.swift
Tests/ProcedureKitCloudTests/CKOperationTests.swift

In Swift 4, `CKOperation.longLived` becomes `CKOperation.isLongLived`.
Match this in ProcedureKitCloud on Swift 4.

Fix: In Swift 4, CKOperation `longLived` -> `isLongLived`

---

Tests/ProcedureKitTests/KVONotificationTests.swift

`Generator.Element` should be `Iterator.Element`

Fix KVONotificationTests compilation [Swift 4]

---

Sources/ProcedureKit/Group.swift
Sources/ProcedureKit/Procedure.swift
Sources/ProcedureKit/Repeat.swift
Sources/ProcedureKit/Retry.swift
Sources/ProcedureKitCloud/CKAcceptSharesOperation.swift
Sources/ProcedureKitCloud/CKDiscoverAllContactsOperation.swift
Sources/ProcedureKitCloud/CKDiscoverAllUserIdentitiesOperation.swift
Sources/ProcedureKitCloud/CKDiscoverUserIdentitiesOperation.swift
Sources/ProcedureKitCloud/CKDiscoverUserInfosOperation.swift
Sources/ProcedureKitCloud/CKFetchDatabaseChangesOperation.swift
Sources/ProcedureKitCloud/CKFetchNotificationChangesOperation.swift
Sources/ProcedureKitCloud/CKFetchRecordChangesOperation.swift
Sources/ProcedureKitCloud/CKFetchRecordZoneChangesOperation.swift
Sources/ProcedureKitCloud/CKFetchRecordZonesOperation.swift
Sources/ProcedureKitCloud/CKFetchRecordsOperation.swift
Sources/ProcedureKitCloud/CKFetchShareMetadataOperation.swift
Sources/ProcedureKitCloud/CKFetchShareParticipantsOperation.swift
Sources/ProcedureKitCloud/CKFetchSubscriptionsOperation.swift
Sources/ProcedureKitCloud/CKMarkNotificationsReadOperation.swift
Sources/ProcedureKitCloud/CKModifyBadgeOperation.swift
Sources/ProcedureKitCloud/CKModifyRecordZonesOperation.swift
Sources/ProcedureKitCloud/CKModifyRecordsOperation.swift
Sources/ProcedureKitCloud/CKModifySubscriptionsOperation.swift
Sources/ProcedureKitCloud/CKQueryOperation.swift
Sources/ProcedureKitNetwork/Network.swift
Sources/TestingProcedureKit/ConcurrencyTestCase.swift
Tests/ProcedureKitTests/GroupTests.swift

Key changes:
- **`GroupProcedure`** child error handling is now centralized in a single **`child(_:willFinishWithErrors:)`** method, which is called for all finishing child Procedures (even if the errors array is empty). The default implementation in `GroupProcedure` appends the received child errors to the Group’s errors.
- **`GroupProcedure`** now uses an internal `GroupProcedureDelegate` object to forward delegate callbacks from its internal queue. Thus, `GroupProcedure` itself is no longer a `ProcedureQueueDelegate` (nor does it expose all the `ProcedureQueueDelegate` methods).
- **`RepeatProcedure`** and **`RetryProcedure`** now override the `child(_:willFinishWithErrors:)` method, providing a clearer execution flow (instead of jumping back-and-forth between multiple different …

Simplify GroupProcedure child error handling behavior & customization

---

Sources/ProcedureKit/Group.swift
Sources/TestingProcedureKit/ConcurrencyTestCase.swift
Tests/ProcedureKitTests/GroupTests.swift

Enables customization of the finishing errors of the GroupProcedure without subclassing.
```diff
open class GroupProcedure {
...
+   public typealias TransformChildErrorsBlockType = (Procedure, inout [Error]) -> Void
...
+   final public var transformChildErrorsBlock: TransformChildErrorsBlockType?
...
}
```
The `transformChildErrorsBlock` is called before the `GroupProcedure` handles child errors.
(It is called on the Group's EventQueue.)
The block is passed two parameters:
- `Procedure`: the child Procedure that will finish
- `inout [Error]`: the errors that the Group attributes to the child (on input: the errors that the child Procedure will finish with)
The array of errors is an `inout` parameter, and may be modified directly.
This enables the customization of the errors that the …

Add `transformChildErrorsBlock` to GroupProcedure

---

.fastlane/Fastfile
Sources/ProcedureKitMac/Process.swift
Tests/ProcedureKitMacTests/ProcessProcedureTests.swift

**ProcessProcedure** now uses an `executableURL` and `currentDirectoryURL` instead of a `launchPath` and `currentDirectoryPath`, matching [deprecations and new properties in `Process` in macOS 10.13](https://developer.apple.com/documentation/foundation/process?changes=latest_minor).
**On macOS 10.13+** (but not earlier macOS versions), ProcessProcedure now uses these URLs to construct the `Process`, and calls the new [`Process.run()`](https://developer.apple.com/documentation/foundation/process/2890105-run?changes=latest_minor) method (which enables it to gracefully handle errors).
The old convenience initializer that takes a `launchPath` (string) and `currentDirectoryPath` (string) still exists. ProcessProcedure falls back to the older method of creating and starting a Process on macOS < …

Modernize ProcessProcedure for macOS 10.13+

---

Sources/ProcedureKit/NetworkObserver.swift
Sources/ProcedureKit/ProcedureEventQueue.swift
Sources/ProcedureKitCloud/CKOperation.swift
Tests/ProcedureKitCloudTests/CKOperationTests.swift
Tests/ProcedureKitTests/NetworkObserverTests.swift

Several conditions that were `#if swift(>=4.0)` should actually be `#if swift(>=3.2)`, as the changes apply even in Swift 3 mode ("Swift 3.2") in Xcode 9.

Revise several #if swift conditions to >= 3.2

---

.ci/buildkite/pipeline.sh
.ci/buildkite/pipeline.template.yml
.ci/buildkite/upload

Turns out that there is a bug in Buildkite where anonymous users are not supported when a build pipeline contains "triggers", such as the one we use to trigger CI in the sister project [TryProcedureKit](https://github.com/ProcedureKit/TryProcedureKit) to perform CocoaPods integration testing.
The solution to this is to either add some more scripting (which I don't want to do). Instead, we'll add a block step, and then a pipeline upload to trigger the job. This will mean that only logged in users (me, and the open source user, can trigger integration testing). I might also limit this to `release/*` branches.

Update CI to fix issue with anon users & triggers in Buildkite 

---

.ci/buildkite/pipeline.sh
.ci/buildkite/upload

Docs are generated with [ProcedureKit/Documentation](https://github.com/ProcedureKit/Documentation) project, on [procedure.kit.run](http://procedure.kit.run/development).

Add trigger to build ProcedureKit documentation

---

Sources/ProcedureKit/Condition.swift
Sources/ProcedureKit/Procedure.swift
Sources/ProcedureKit/ProcedureQueue.swift

In which Condition evaluation (or the Procedure which has the Conditions) could become stalled and never complete / execute.
The cause appears to be a race condition / bug / quirk in how `NSOperation(Queue)` handles dependencies (specifically, how it handles `isReady` changing while an Operation is being added to the queue).
For more, see #755

Fix (rare) race conditions involving Conditions

---

Sources/ProcedureKit/AnyObserver.swift
Sources/ProcedureKit/Procedure.swift

This is an alternative WIP to #753 that should maintain essentially all backwards-compatibility with existing code. 
**New functionality:**
- Catches incompatible Observers at run-time and provides helpful debug / logging output.
(So it theoretically could go into a ProcedureKit v4 point release, while the more significant / breaking changes in #753 are further-discussed.)
Thoughts and feedback appreciated.

Resolve ProcedureObserver errors on Xcode 9 beta 3

---

README.md

Really not sure what the plan with the migration is, since I read all the old docs and found them beneficial but uncomfortable. 
Or maybe I have missed something glaringly obvious about what is going on. 
In any case I thought you may have not yet got the time to add the link.

[Documentation]: Link to reference docs

---

Tests/ProcedureKitTests/ProfilerTests.swift

Previously, there was no guarantee that the produced child would finish before the wait completed.

Fix unstable test: `test__profile_operation__which_produces_child`

---

Tests/ProcedureKitTests/BlockObserverTests.swift
Tests/ProcedureKitTests/ProfilerTests.swift

- Fixes unstable test: `test__did_cancel_synchronized`
- Fixes unstable test: `test__did_cancel_is_called`
- Fixes unstable tests: `ProfilerTests`

Fixes unstable tests

---

Sources/ProcedureKit/MutualExclusion.swift
Sources/ProcedureKit/Procedure.swift
Sources/ProcedureKit/ProcedureQueue.swift
Tests/ProcedureKitStressTests/ProcedureStressTests.swift
Tests/ProcedureKitTests/ConditionTests.swift
Tests/ProcedureKitTests/MutualExclusivityTests.swift

- Condition evaluation now properly waits until the associated ProcedureQueue is not suspended to begin.
- An edge-case bug involving Mutual Exclusivity and ProcedureQueue suspension is now resolved.
- Added lots of additional tests involving condition execution timing and mutual exclusivity.
References: #792

Fix issues with Conditions and suspended ProcedureQueues

---

Sources/ProcedureKit/Collection+ProcedureKit.swift
Sources/ProcedureKit/Group.swift
Sources/ProcedureKit/Operation+ProcedureKit.swift
Sources/ProcedureKit/Procedure.swift
Tests/ProcedureKitTests/GroupTests.swift
Tests/ProcedureKitTests/ProcedureTests.swift

Will deprecate `userIntent` property, and remove it's usage. Particularly from `GroupOperation`.

UserIntent causes Data Race

---

Sources/ProcedureKit/ProcedureResult.swift
Sources/ProcedureKit/Repeat.swift
Sources/TestingProcedureKit/TestProcedure.swift
Tests/ProcedureKitTests/RepeatProcedureTests.swift
Tests/ProcedureKitTests/RetryProcedureTests.swift

This PR adds full support for using _result injection_ techniques with `RepeatProcedure` (and it's subclasses, `RetryProcedure`) when the associated "Payload" Procedure type conforms to `InputProcedure`.

Support for InputProcedure in RepeatProcedure etc

---

Sources/ProcedureKit/Repeat.swift
Sources/ProcedureKit/Retry.swift
Tests/ProcedureKitTests/RetryProcedureTests.swift

A common usage is likely, to just try the operation again, therefore an init which takes:
- max count
- wait strategy
- operation closure

Expose convenient initialiser for Retry

---

ProcedureKit.xcodeproj/xcshareddata/xcschemes/Mac.xcscheme
ProcedureKit.xcodeproj/xcshareddata/xcschemes/iOS.xcscheme
ProcedureKit.xcodeproj/xcshareddata/xcschemes/tvOS.xcscheme

By removing the actual framework targets from the three platform test schemes, Carthage will avoid building them when bootstrapping / updating a project that depends on ProcedureKit. 
These changes fix #863.
Based on what I can see, the changes to the schemes should have no affect on installation via CocoaPods or SPM.

Make new platform schemes used by CI test only schemes.

---

.ci/buildkite/pipeline.sh
.ci/scripts/test-cocoapods
.gitignore
Integrations/CocoaPods/Podfile
Integrations/CocoaPods/Podfile.lock
Integrations/CocoaPods/TryProcedureKit iOS/AppDelegate.swift
Integrations/CocoaPods/TryProcedureKit iOS/Assets.xcassets/AppIcon.appiconset/Contents.json
Integrations/CocoaPods/TryProcedureKit iOS/Base.lproj/LaunchScreen.storyboard
Integrations/CocoaPods/TryProcedureKit iOS/Base.lproj/Main.storyboard
Integrations/CocoaPods/TryProcedureKit iOS/Info.plist
Integrations/CocoaPods/TryProcedureKit iOS/ViewController.swift
Integrations/CocoaPods/TryProcedureKit iOSTests/Info.plist
Integrations/CocoaPods/TryProcedureKit iOSTests/TryProcedureKit_iOSTests.swift
Integrations/CocoaPods/TryProcedureKit.xcodeproj/project.pbxproj
Integrations/CocoaPods/TryProcedureKit.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Integrations/CocoaPods/TryProcedureKit.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Integrations/CocoaPods/TryProcedureKit.xcodeproj/xcshareddata/xcschemes/TryProcedureKit.xcscheme
Integrations/CocoaPods/TryProcedureKit.xcworkspace/contents.xcworkspacedata
Integrations/CocoaPods/TryProcedureKit.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Integrations/CocoaPods/TryProcedureKit.xcworkspace/xcshareddata/TryProcedureKit.xcscmblueprint
Integrations/CocoaPods/TryProcedureKit/AppDelegate.swift
Integrations/CocoaPods/TryProcedureKit/Assets.xcassets/AppIcon.appiconset/Contents.json
Integrations/CocoaPods/TryProcedureKit/Base.lproj/Main.storyboard
Integrations/CocoaPods/TryProcedureKit/Info.plist
Integrations/CocoaPods/TryProcedureKit/ViewController.swift
Integrations/CocoaPods/TryProcedureKitTests/Info.plist
Integrations/CocoaPods/TryProcedureKitTests/TryProcedureKitTests.swift
Sources/ProcedureKitNetwork/NetworkData.swift

At the moment, there are integration tests for CocoaPods in a different repository (https://github.com/procedurekit/tryprocedurekit) which causes difficulty in CI in some scenarios
- builds from 3rd party forks don't work
- it can be tricky to make changes in PK which need to be reflected in TryProcedureKit too in order to pass.
So, it would be better to just have an `integrations/` directory in here with some projects which integrated ProcedureKit from the local directory (i.e. `../`).

Move TryProcedureKit integration tests into main repo

---

Sources/ProcedureKit/Block.swift
Tests/ProcedureKitTests/BlockProcedureTests.swift

The `sub` procedure never properly finishes due to a typo with finishing block names.

Fix bug with UIProcedure

---

Sources/ProcedureKitMobile/ViewControllerContainment.swift

At the moment, it has defaulted to internal - so not possible for framework consumers to use.

Make auto layout containment strategy block property public

---

ProcedureKit.xcodeproj/project.pbxproj
README.md
Sources/ProcedureKit/Block.swift
Sources/ProcedureKit/Result.swift
Tests/ProcedureKitTests/BlockProcedureTests.swift

Refactor BlockProcedure

---

ProcedureKit.xcodeproj/project.pbxproj
Sources/ProcedureKitCoreData/InsertManagedObjects.swift
Sources/ProcedureKitCoreData/ProcessManagedObjectContext.swift
Tests/ProcedureKitCoreDataTests/InsertManagedObjectsProcedureTests.swift
Tests/ProcedureKitCoreDataTests/ProcedureKitCoreDataTests.swift

Following discussion in #903.
This ticket introduces a (currently) internal class to perform MOC processing. Essentially it's a `GroupProcedure` subclass which will create an MOC, set it on a "processing" class (via protocol conformance), and then save the MOC.
This means, that the `InsertManagedObjectsProcedure` public class, is just a thin wrapper responsible for defining the "processing" class.
One benefit of this, is that all the handling of the MOC is entirely inside the class on the same `DispatchQueue`.

Refactors InsertManagedObjectsProcedure

---

Sources/ProcedureKit/ProcedureObserver.swift

The Xcode auto-completes the `ProcedureObserver` methods with `with` preposition without the appropriate variable name.
```swift
func did(finish procedure: Procedure, with: Error?) {
if let error = with { // ??? clearly a mistake
}
}
```

Add variable name in signatures that include "with: Error?"

---

Sources/ProcedureKit/Procedure.swift
Sources/ProcedureKit/ProcedureObserver.swift
Sources/ProcedureKit/ProcedureProcotol.swift

There is a missing `error` parameter name in various functions.
It's needed as the code looks weird without it:
Before:
```swift
override func procedureDidFinish(with: Error?) {
guard with == nil else { return }
...
}
```
After:
```swift
override func procedureDidFinish(with error: Error?) {
guard error == nil else { return }
...
}
```

Add missing  parameter name in various functions

---

Sources/ProcedureKitNetwork/Network.swift
Sources/ProcedureKitNetwork/NetworkSupport.swift

This merge request opens the NetworkRecovery<T> class, allowing customized recovery logic when network procedures fail. 
This makes handling cases when network procedures fail, and are recoverable, but require additional configuration, for example requests that have failed (401) using Oauth, which are possibly recoverable using a refresh token:
```swift
class AuthenticatedNetworkRecovery: NetworkRecovery<SecuredNetworkProcedure> {
let authManager: AuthManager
init(authManager: AuthManager) {
self.authManager = authManager
super.init(resilience: DefaultNetworkResilience(), connectivity: .any)
}
override func recover(withInfo info: RetryFailureInfo<SecuredNetworkProcedure>, payload: RepeatProcedurePayload<SecuredNetworkProcedure>) -> RepeatProcedurePayload<SecuredNetworkProcedure>? {
let …
```

Open network recovery

---

.ci/buildkite/pipeline.sh
.ci/scripts/test-spm
.gitignore
Integrations/SPM/.gitignore
Integrations/SPM/Package.swift
Integrations/SPM/Sources/SPM-Integration-Check/main.swift
Integrations/SPM/Tests/SPM-Integration-CheckTests/SPM-Integration-CheckTests.swift
Sources/ProcedureKit/Block.swift

Failing to build in SPM due to missing Foundation import

---

Sources/ProcedureKitMac/Process.swift

Without a public init method, a LaunchRequest cannot be created, but is required by the designated initializer.

Adds public accessor modifiers to LaunchRequest
